### ISSUE TITLE
Room class structure

### ISSUE THREAD

**Issue by Turtyo** [Saplings-Projects/1M_sub#10]
## Feature Description

What should be the structure of the `Room` class ? 

## Motivation

Rooms being the most basic element of the map should have a carefully thought structure, since the entire map is just assembling rooms.

## Acceptance Criteria

Tests should pass.

## Proposed Solution

Rooms have the following elements:
- an integer to know the light level (0 being unlit, 1 is dimly lit, 2 is lit, 3 is brightly lit), could also be an `ENUM`
- a boolean to know if a torch is in the room (but maybe we want to let the player put multiple torches in a room ?)
- an event ( #20 )

## Additional Context

This issue is in link with the map implementation #6

**Comment by cheesefrycook** [comment]
Makes sense to me. I think the Room can extend from Resource similar to CardBase. Then the Map can generate a list of Room when the run starts. Then when we want to display the map to the player, we initialize a bunch of RoomWorld with the data from the Room array. RoomWorld can be a Node2D/Control node that just holds Room data and displays it. Having the separate Room and RoomWorld structure like this will let us load/unload the map display, while keeping the actual data stored in the array in Map.

**Comment by Turtyo** [comment]
Let's call it `RoomDisplay` then.

**Comment by Turtyo** [comment]
I think the display will be made in another PR and not in the initial room implementation
