### ISSUE TITLE
Draw pile and discard pile

### ISSUE THREAD

**Issue by cheesefrycook** [Saplings-Projects/1M_sub#11]
## Feature Description

Add a draw pile and discard pile. Add global drawing and discarding of cards. Allow CardBase to draw and discard cards.

## Motivation

There is no concept of draw pile and discard pile. Additionally, there is no way to have cards drawn or discarded from other cards. For example, a card with the effect "Draw 2 cards"

## Acceptance Criteria

- CardBase allows drawing and discarding of cards via parameters (amount_of_cards_to_draw, amount_of_cards_to_discard)
- When cards are played, they are added to a discard pile
- When the draw pile is empty, the discard pile is shuffled into the draw pile
- Cards are put into the player's hand from the draw pile

## Proposed Solution

The draw pile and discard pile are stored in CardContainer as arrays of CardBase, NOT CardWorld. When ready to draw we get the top CardBase from the draw pile array and initialize a new CardWorld with that data.

Modify CardManager to hold a reference to the current CardContainer. If you wish to draw cards from somewhere, call `CardManager.card_container.draw_cards()`

**Comment by Turtyo** [comment]
> Add global drawing a discarding of cards

Little typo maybe ?

- Why have `CardBase` be the one that holds the ability to draw cards ?
- How many draw by turn ? Can this value be modified by the player in some way ?
- The action to shuffle the discard pile in the draw pile should be possible when implementing (for example you draw 2 but you have only 1 left in draw pile)
- Someone mentioned having the discard pile be called `compost`, I like the idea, what do you think (ofc we won't call it like that in the code, but for a visual indication it could be nice)

**Comment by cheesefrycook** [comment]
Which typo are you referring to? 
- Yes, my idea is CardBase should allow drawing of cards. For example, a card with the effect "Draw 2 cards". We could do this in children of CardBase, but I feel card drawing will be something that a lot of cards will want, so it may be easier to do in the parent like I'm suggesting here. So we have params on the CardBase like `amount_of_cards_to_draw` `amount_of_cards_to_discard` that can be easily set. Similar to how CardBase can deal damage right now with the `damage_to_deal_to_target`
- My idea is to start with 5 cards drawn per turn
- I think I made a typo on the original. The discard pile should shuffle into the draw pile when there are no cards left to draw.
- Love the idea!

**Comment by Turtyo** [comment]
"Add global drawing a discarding of cards" doesn't really make sense to me, I would've expected "Add global drawing **and** discarding of cards" for example

- Do you mean "discard of cards when your turn ends" ? Also, if `CardBase` is already able to draw cards from other card effect, why not let it be the one that handle the draw phase at the start of the turn too ? Because it not, that means we would have a function that draws for the turn start, and one that draws due to effects, it seems a bit messy since both do the same thing.
- Alright for 5, can it be changed in any way by the player ? I would say yes, that could be an item effect or a card effect
- Do we agree that the shuffle will only be called when it **sees** that there are no more cards to draw ? It won't check before that the number of cards that are to be drawn is smaller that the number of cards to draw. Because if we do that, the problem is that we would shuffle when there are still cards in the draw pile, which could lead to not getting the cards we would have gotten otherwise. Example, you have cards A in draw, B and C in discard and you draw 2. You first draw A then you shuffle, and not check, see there are not enough, shuffle, which could lead to drawing B and C

**Comment by Turtyo** [comment]
- If we make the draw function in `CardContainer`, why call it from `CardBase` ? Couldn't cards that draw be their own class and call `CardContainer` directly ?

And we agree on the next two points.

**Comment by cheesefrycook** [comment]
I suppose we could make a child Card_DrawCards if we want to reduce bloat in CardBase. I just figure it makes more sense to have CardBase provide a lot of common functionality across different cards. For example, if we want to have a card like "deal 3 damage, draw 2 cards" all we have to do is create a new child of CardBase and set the properties.

**Comment by cheesefrycook** [comment]
We could try to do some multi hierarchy thing, but I really think it over complicates things. Maybe it’s better to think about it like this: CardBase handles **actions**, while children handle unique **applications of those actions**. Actions are things like dealing damage, applying a buff/debuff, drawing cards, or restoring AP. In the CardBase, we're handling the application of those actions whenever the card played. In child cards, you could override the application in your own unique way. Some examples of unique action application:
- Apply poison to all targets. If the target is at full health, apply 2 extra poison
- Apply damage equal to your current AP
- Deal 3 damage. If the enemy has a debuff, gain +1 AP

Each of the above cards has an action that is played in a unique way rather than "do X as the card is played". Maybe we can make a new issue that modifies naming to make things more clear.

Just as a note, the CardBase does handle the poison buff at the moment with `buffs_to_apply_to_target`

**Comment by Turtyo** [comment]
From OOP standpoint, parent class should only have methods that are used by every children class. If we want something specialized then we create a children class. Because for example a poison effect doesn't need to have a "draw card" method in its parent class.

**Comment by cheesefrycook** [comment]
Sure, I suppose this goes against OOP. But the alternative methods I can think of either require us to rewrite a lot of code in child cards, or have a complicated multi class hierarchy. I like this method because it's simple.
Want to create a new card? See if you can do it by setting properties on the CardBase. Can't do that? Create a new child of CardBase that does it.
Do you have any ideas for a system that stays within OOP principles that both remains simple and won't require much code rewrite in children?

**Comment by Turtyo** [comment]
I think this should be discussed in a new issue, I will open one.

**Comment by cheesefrycook** [comment]
Okay. Is this issue good to go ahead and implement?

**Comment by Turtyo** [comment]
Well we can have the draw be as you described in this issue for now, but it will probably change later due to #14 
You can go ahead and implement this one if you'd like.
