### ISSUE TITLE
Deck animation and layout

### ISSUE THREAD

**Issue by cheesefrycook** [Saplings-Projects/1M_sub#12]
## Feature Description

Add a dealing and discarding animation for cards. Add fan-shaped layout for cards. Add animation for hovering cards.

## Motivation

I feel it's important to get card animation integrated early. Since the animation will have cards added and discarded one by one, this could lead to issues where we're trying to access cards that aren't properly initialized or destroyed yet.

The fan-shaped layout is a visual change. It will make large hand sizes easier to see.

## Concept art / Designs

Proposed card layout from Slay the Spire.
<img width="596" alt="Screenshot 2023-12-07 172524" src="https://github.com/Saplings-Projects/1M_sub/assets/151570126/ef5d0c28-a2f9-4f61-a1a2-226dc351f9b2">

## Acceptance Criteria

- Cards are dealt in a fan shape
- Cards are dealt one by one and discarded one by one
- Interacting with cards during dealing and discarding does not result in unexpected states
- Hovering a card scales it up and moves other cards out of the way

## Proposed Solution

Cards can be dealt and removed on a looping timer. When you want to add or discard a card, it can be added to a queue to be added/removed on the next timer tick. For discarding, adding to a queue prevents the card from remaining in the hand after the card is already played.

Cards have a `CardMovementComponent` which is a state machine. Each state can have its own movement code. `CardMovementComponent` has a `desired_position` which is set from the `CardContainer`. States can also be switched from the `CardContainer`. We want to do this in the `CardContainer` because it has a list of all the cards in the player's hand. This allows us to set the `desired_position` of the cards relative to all other cards.

The fan-shaped layout can use curves with the card's input x-position to modify either rotation or y-position.

## Implementation Steps (Optional)

- Implement `CardMovementComponent`
- Implement card drawing and discarding queue
- Implement fan-shaped layout
- Implement card hover states

## Additional Context

Dependent on #11

**Comment by Turtyo** [comment]
What would the movement of the cards be ? Straight line from the draw to the hand and straight line from the hand to the discard ? I think it's a good idea to start with a simple motion like that.
How do you plan to make `CardMovementComponent` ?
I think timers for draw and discard should probably be different (discard faster than you draw ?)

**Comment by cheesefrycook** [comment]
- Yes a simple animation like that to start with. Maybe also scale the card up from zero.
- `CardMovementComponent` will be made up of states. Like `MOVING_TO_HAND` `QUEUED` `DISCARDING`. Then we can have functions for when the states switch `state_enter()` `state_process()` and `state_exit()`. We can check what our current state is in each of the functions using a `match` statement, then do whatever custom movement we like. It's nice doing it in a state machine like this because you know the card is only going to do one type of movement at a time.
- I agree, slower drawing, fast discard

**Comment by Turtyo** [comment]
There are quite a list of things, could you maybe do a little schematic to show organization of classes / where the code will be ?
It's just to make sure we agree on everything, but it seems like we do.

**Comment by cheesefrycook** [comment]
Sure, I think that'll be helpful. I can do a quick sketch

**Comment by cheesefrycook** [comment]
Let me know if I should provide more detail

![CardMovement](https://github.com/Saplings-Projects/1M_sub/assets/151570126/fee75120-23a0-41c0-89fb-3ed7c369e0d8)

**Comment by Turtyo** [comment]
`CardWorld` already contains the position of the hand doesn't it ? It should probably include draw and discard positions as well.

Apart from that, it seems clear to me.

**Comment by cheesefrycook** [comment]
It wouldn't include the position of the hand no. A card doesn't know about the greater hand, that's controlled by the CardContainer

**Comment by Turtyo** [comment]
I got confused with `CardContainer`. Maybe `CardContainer` should be renamed to `CardHand` in the future

**Comment by cheesefrycook** [comment]
That's correct yes

**Comment by Turtyo** [comment]
Alright, once #11 is good do you want to do this ?

**Comment by cheesefrycook** [comment]
Yes please!
