### ISSUE TITLE
Fix block to use new phases

### ISSUE THREAD

**Issue by JonaLam** [Saplings-Projects/1M_sub#120]
## Is your amelioration related to a problem? Please describe.

The way block is removed at the start of the turn is with a temporary signal in the phase manager.
That signal should be removed and the block should be removed in a newly implemented remove block phase

## Additional context
#114 needs to be done
#118 needs to be done

**Comment by Turtyo** [comment]
I would consider that a bug since it doesn't behave as we would like it

**Comment by Turtyo** [comment]
Once #124 is merged, I think the plan would be to add two block remove phases (one for player, one for enemies). When on this phase, we call the `block_reset` of `health_component`

Or we can do it via signal, but it's harder to debug than direct function calls I think (because with direct calls you have a clear stack trace)

**Comment by Turtyo** [comment]
Okay, now that #124 is merged, I'm thinking of this solution:
- Add two new phases: `reset_block_ally` and `reset_block_enemy`
- In the battler:
    - `reset_block_ally`: reset the block of the player by  calling `block_reset` for the `health_component` of the player
    - `reset_block_enemy`: reset the block of all the enemies in the same way
After each phase we call the `advance_to_next_combat_phase` to go to next phase
I'm thinking of putting the reset for ally just before the player turn (so effects like poison still damage the player). And in a similar fashion for the enemies

I'm also thinking that we might want to separate the effects of start and end of turn into their own phase. This way if later we want to move stuff around, it's easier. That way, the player phase is reserved for player interaction with cards, and everything that is automatic (effects triggering) is in its own phase

Later if we decide we want the block to last until after the turn start effects (thus meaning we can block poison for example), we just need to exchange the position of the remove block and the effect of the turn start (which I don't think we can do currently, as everything is in the player turn for that matter)
