### ISSUE TITLE
Soft-locking game when exiting room selection at game start

### ISSUE THREAD

**Issue by Turtyo** [Saplings-Projects/1M_sub#122]
## Describe the bug
When escaping the map at game start, it results in a screen with nothing on it.

## To Reproduce
1. Start a new game
2. This opens the map, do not click on anything and just press "escape" on your keyboard
3. This closes the map
4. Now the screen is just grey, with nothing to do

## Expected behavior
No soft-lock possible from starting the game

## Possible solution
Either of those would work
1. Disable escaping the map at the start of the game
2. Add the overlay with map button

Preference for solution 1, because there is no reason for a player to escape the map upon game start

**Comment by Turtyo** [comment]
@Biosquid I see you took this issue a week but haven't actually discussed how you plan to do it or approve the issue.
Which of the two solution I described would you go for ? Do you have another solution perhaps ?

**Comment by Biosquid** [comment]
I was planning on going w/ the first. It seems easier to implement and has the lowest chance of causing any other issues in the future as long as we find a good spot to re-enable it.

**Comment by Turtyo** [comment]
You can probably re-enable it when the player clicks a room. i'm not too sure how to disable a key mapping, you'll have to see that for yourself

**Comment by Biosquid** [comment]
@Turtyo I went over this issue w/ @BishopJohnson and we got it fixed and I pushed it to my fork.

Bishop also recommended that we change the queue_free() method to be _on_return_button_pressed() instead as it can be better in the long run if we want to go somewhere specific when escape is hit (i might be wording it badly but i think thats the general idea). What do you think about this?

**Comment by Biosquid** [comment]
I should note that I fixed it by just not allowing the method to run if map is the only scene, so it'll work if we change things in the future to go to the map only view after each fight/event/shop/whatever

**Comment by Turtyo** [comment]
Which `queue_free` are you referring to ? There are multiple inside the code, which file are you talking about ?

Regarding what you did, it would be easier if you made a pull request, as it's easier to show what you did instead of saying what you did. If you think the PR is not ready for merge, open it as a draft PR
