### ISSUE TITLE
Opening inventory and going back to main menu leaves inventory open in main menu

### ISSUE THREAD

**Issue by Turtyo** [Saplings-Projects/1M_sub#130]
## Describe the bug
As per the title

## To Reproduce
- Start a game
- When in a combat event (the only event from which you can go back to the main menu, might change with #123 ), open the inventory
- Now click on "back to main menu"
- The inventory is still open in the main menu

Note that this disappears upon starting a new game.

## Expected behavior

The inventory screen should disappear when going back to the main menu

## Screenshots
![image](https://github.com/user-attachments/assets/752f539c-0051-43b1-83cc-407fd808c05f)
![image](https://github.com/user-attachments/assets/cf99c9d7-5a53-4a7a-a0f4-3436ac3a85f6)

## Environment
 - OS independent
 - commit 9df0eb3

**Comment by Turtyo** [comment]
Might be due to the inventory not being attached to the tree of the current scene, and thus not being exited when going back to the main menu; this will need to be checked, but that would explain this behavior

**Comment by Turtyo** [comment]
@Biosquid i notice you assigned to this, what do you plan to do ? i think a good thing would be to first identify the source of the bug and then write it here so we can discuss of the solution

**Comment by Biosquid** [comment]
Just confirmed the issue! How would I go about confirming the source of the bug, by checking what its attached to? In that case you are correct, its attached to "InventoryManager" which attached to root. Do you think it a good fix for this issue would be to move the "InventoryHUD" scene to the fight or move the entire "InventoryManager" scene?

**Comment by Turtyo** [comment]
The inventory manager is an autoloaded singleton so it's never exited;
Two solutions i can think of:
1. attach the `InventoryHUD` to the current scene
2. keep it on `inventoryManager`, but think of closing it when exiting the current scene

I'm more for solution 1 because that kinda ensures we don't have to think about other ways / interactions to do it.

**Comment by Biosquid** [comment]
Yea I'll go with 1, that's what i was leaning towards anyways.
