### ISSUE TITLE
opening the inventory makes it so you can't press on anything

### ISSUE THREAD

**Issue by JonaLam** [Saplings-Projects/1M_sub#136]
## Describe the bug
When you open the inventory you can't press anything else

## To Reproduce
Open up any non-combat event scene and open the inventory. The game should lock up

**Comment by Turtyo** [comment]
As this is not a bug in the combat, I'm guessing it might have something to do with not having a control node left available on the screen (which is not the case on the combat).
Might be wrong, but I think we should try to do the interface of the shop and other events before checking this ? unless we can find an easy solution

This is also a problem with the dialogue event, which is more of a problem

**Comment by Turtyo** [comment]
Since decided to not use items and consumables, we can make a fix by avoiding the problem, meaning we remove the button to display the inventory, and we just put a label displaying the amount of gold
We  can find the reason for this problem later with the full inventory.

This will both solve the problem, and do it quickly

**Comment by Biosquid** [comment]
took a look at the code last night, will try to implement the fix tonight as it doesn't seem to bad at all. Do you want the gold cost in any specific file or should I make a new script (i mean gd file just in case im using the wrong terminology)? I imagine I can just add it on somewhere as its a more simple change

**Comment by Turtyo** [comment]
There is already a method to display the amount of gold somewhere. Add a label and set the value of the label through code. You can put the `.gd` script file inside `UI/` (as that's where the other button of the overlay have their scripts).
I'm not sure there is a signal that's emitted when gold is changed, if not you need to create one, and put it at the correct place so the label is updated if needed.
