### ISSUE TITLE
Move `tests/unit/` to `Tests/`

### ISSUE THREAD

**Issue by Turtyo** [Saplings-Projects/1M_sub#15]
## Is your amelioration related to a problem? Please describe.

All tests should be in the same folder, but #8 puts them in `tests/unit/`

## Describe the solution you'd like
Just move everything from `Tests/` into `tests/unit/` and delete `Tests/`

## Describe alternatives you've considered
We could put everything into `Tests/` but the action is already made to use `tests/unit/`

## Additional context
To do once #8 closes.

**Comment by cheesefrycook** [comment]
Sounds good to me

**Comment by Turtyo** [comment]
Or should we put `tests/unit/` in `Tests/` instead ?

**Comment by cheesefrycook** [comment]
I don’t really have a preference
