### ISSUE TITLE
Add UI popup for draw/discard pile

### ISSUE THREAD

**Issue by cheesefrycook** [Saplings-Projects/1M_sub#18]
## Feature Description

Adds a UI popup that shows all the cards in the draw or discard pile on click. It will show all the cards in a grid.

## Motivation

Currently there is no way for a player to view what is in the discard pile or draw pile.

## Concept art / Designs

![image](https://github.com/Saplings-Projects/1M_sub/assets/151570126/098c46a3-8ff6-4ce1-991e-ec8f2c264715)

## Acceptance Criteria

- Clicking the draw pile shows a grid of all the cards in the draw pile
- Clicking the discard pile shows a grid of all the cards in the discard pile
- Clicking the back button when on the UI popup will take you back into the game
- Each UI popup is scrollable
- You cannot interact with the game while the UI popup is on screen

## Proposed Solution

Use a GridContainer Control Node to lay out the cards. Use a ScrollContainer Control Node to provide scrolling functionality. Populate the container by creating an instance of CardWorld and providing CardBase data to `init_card()`. Clicking either the draw pile or discard pile button will create a new CardScrollUI popup scene. Pressing the back button in this scene will destroy the scene.

## Implementation Steps (Optional)

-Add CardScrollUI scene
-Initialize scene when draw/discard button is pressed
-Destroy scene when back button is pressed
-Populate scene with either draw pile or discard pile based on what button was clicked. Use the `CardPileUISetter` for this, and obtain the draw pile or discard pile via `CardManager.card_container.draw_pile`

## Additional Context

Depends on #17

**Comment by Paper-2** [comment]
The order should be an arbitrary one, like card rarity, energy cost, or alphabetical order. I don't think the player will have fun knowing what cards they will get next.

**Comment by Paper-2** [comment]
Also this issue should deal with making an UI for the player inventory, which is all the cards that the player has obtained.

**Comment by Turtyo** [comment]
Yes it can be the same as the inventory, since  the only difference is where you call it from

**Comment by cheesefrycook** [comment]
That’s a good point. Maybe this issue should include adding a “deck view” button which shows your whole deck?

**Comment by Paper-2** [comment]
Yes, That's I meant by an inventory. I should of said " ... player has obtained in the current run." instead of just "... player has obtained."

**Comment by cheesefrycook** [comment]
If you'd like to do that in this issue, you can just use `default_deck` from CardContainer

**Comment by Turtyo** [comment]
Basically we have a class that displays a set of cards (whether that is the complete deck, the draw or discard pile). And you can call it from those contexts.
