### ISSUE TITLE
Add a Status class to be parent of Buff/Debuff

### ISSUE THREAD

**Issue by Turtyo** [Saplings-Projects/1M_sub#2]
**Is your feature request related to a problem? Please describe.**
Right now the debuff and buff are all under the same `BuffBase` class. This can lead to confusion as we might not know later what we are doing. We might also want to differentiate between the two for a question of priority / UI design.

**Describe the solution you'd like**
Creating a parent class called `Status` or `StatusEffect`, and make both `Buff` and `Debuff` extend this class. Most of code would be in the `Status` class since for the coding part of it, they do pretty much the same thing (they have an effect on the characters)

**Describe alternatives you've considered**
An alternative would have been to keep the `BuffBase` class and having a `bool is_debuff`. The issue with this is that it's probably less clear than having two distinct classes. It also doesn't allow for static typing checks at compilation.

**Additional context**
For the UI, it was suggested to have debuffs with a red border and buffs with a green border as an indicator (not clear if this is a flashing effect on the border of the screen when the effect is applied, or if this is the color of card border which gives this status).
This has been discussed as something that could be done with [this PR comment](https://github.com/Saplings-Projects/1M_sub/pull/1#discussion_r1412344670) and was decided to be implemented in another PR, since this is out of the scope of the initial PR.

**Comment by cheesefrycook** [comment]
Makes sense
