### ISSUE TITLE
Reformat `test_health.gd` so it uses a card as if it was being played

### ISSUE THREAD

**Issue by Turtyo** [Saplings-Projects/1M_sub#26]
## Is your amelioration related to a problem? Please describe.

Currently, `test_health.gd` is testing by directly changing the values of health (with `DealDamageData.new()` and `_player_health_component.deal_damage(deal_damage_data)`). This was good for a first test, but this is not how a player will interact with the game. When I was writing card effects, the tests were passing but the cards didn't deal any damage at all (because the implementation was incomplete at the time I tested it by launching the test scene).

## Describe the solution you'd like
Reformat the test so that it uses cards with effects (after #14 is closed), instead of directly dealing the damage via function call.

## Describe alternatives you've considered
Make another test that tests the cards in themselves, that way we can test separately the functions that deal damage from the thing that calls them (eg the cards)

## Additional context
Needs #14 to be closed by PR

**Comment by cheesefrycook** [comment]
Sounds good to me!

**Comment by Turtyo** [comment]
Would we change `test_health` or do we create a new test file ?

**Comment by cheesefrycook** [comment]
Yeah we may as well create a new test file. Like test_effects.gd or something, and we can test a bunch of different cards in there

**Comment by Turtyo** [comment]
Or maybe we rename test_card to test_draw instead, and the new test_card file actually tests the cards

**Comment by Tysterman74** [comment]
"amelioration" is such a fancy word I didn't even know about it until reading this. I'd love to take this one once #14 is done, gives me a chance to dive into the unit tests a bit more!

**Comment by Turtyo** [comment]
It didn't seem that fancy to me, but probably because it's often used in french... I could have said "betterment", "improvement" or such... Or enhancement
I can change the template if this word is unclear / it might give trouble to some people
