### ISSUE TITLE
Add an `@Override` comment for classes that extend from a parent class

### ISSUE THREAD

**Issue by Turtyo** [Saplings-Projects/1M_sub#3]
**Is your feature request related to a problem? Please describe.**
Sometimes, it is confusing when reviewing code to have to remember if a function has been declared by a parent Class and is just being override in the children class.

**Describe the solution you'd like**
Even if GDScript doesn't have an `@Override` like other languages, it would be useful to add this (or another notation) to make it clear that the function comes from the parent class.

**Additional context**
This has been discussed as something that could be done with [this PR comment](https://github.com/Saplings-Projects/1M_sub/pull/1#discussion_r1412349391) and was decided to be implemented in another PR, since this is out of the scope of this initial PR.

**Comment by cheesefrycook** [comment]
I agree. A standard comment that's consistent would be nice

**Comment by Turtyo** [comment]
Will also add to the CONTRIBUTING.md so that it stays like that for future code implementations.
