### ISSUE TITLE
Enemy Turn executing while we're in the middle of ending turn and discarding hand

### ISSUE THREAD

**Issue by Tysterman74** [Saplings-Projects/1M_sub#34]
## Describe the bug
From https://github.com/Saplings-Projects/1M_sub/pull/25 and the introduction of the discard animation there is a bug where the enemy turn will start while the player's hand is going through the discard animations.

## To Reproduce
1. While on Player Turn with a full hand (more cards the better)
2. Click on End Turn to switch to Enemy Phase
3. Observe cards going through discard animation into the discard pile
4. Observe that Fauna player takes damage while discarding is happening

## Expected behavior
Wait for Discard Animation to finish before we switch over to Enemy Phase.

## Screenshots
I'm writing this on my phone but you can check https://github.com/Saplings-Projects/1M_sub/pull/25 Cheese has a video on the Additional Notes section.

## Environment
 - currently on PR #25 but should be in main branch once merged 

## Additional context
Known issue from PR #25, but made this issue to split out this fix to prevent the PR from having to wait for a fix. It's not necessarily a showstopper so we're okay with splitting out the work to fix, and #25 is dependent on a few other PRs that are waiting to be merged as well so we'd like to get #25 merged to unblock other PRs.

**Comment by Tysterman74** [comment]
My solution for fixing this is to add a new Phase in our Phase enums called PLAYER_FINISHING, which is meant to define clean up that we would want the player to do. We would create a new signal that is emitted in CardContainer.gd and connected to in Battler.gd that will trigger when all of the animations are finished. The signal would be emitted in _handle_discard_queue in CardContainer.gd but also have a check on the current phase that it's in. _handle_discard_queue is currently used whenever we play a card and when we want to discard all of our hand after ending turn so we would have to check for the new Phase before emitting the signal.

IMO this issue seems kind of smallish enough that if anyone interested wanted to get their hands dirty with the code can take up. I can assist them with implementation. But if no one wants it I'm more than happy to take it over.

**Comment by cheesefrycook** [comment]
This sounds good to me, I think adding a new phase is a good approach. So instead of setting phase to `ENEMY_ATTACKING` when you click the End Turn button, it sets to `PLAYER_FINISHING`. Then we can switch to `ENEMY_ATTACKING` in the CardContainer when everything is discarded
