### ISSUE TITLE
Card casting animations

### ISSUE THREAD

**Issue by cheesefrycook** [Saplings-Projects/1M_sub#38]
## Feature Description

Each card should have the ability to play a unique animation when cast. This can include anything from animated sprites, particles, screen effects, or sounds.

## Motivation

- Cards have no way to play animations when cast.
- Cards play effects immediately instead of in a sequence. Playing each effect in sequence will be more clear to the player.

## Acceptance Criteria

- Cards should have the ability to play a unique animation for each effect.
- Cards play each associated animation in sequence.

## Proposed Solution

Casting animations can be `PackedScenes`. This is flexible, and allows us to do whatever we want for the animation - like particles, screen effects, animated sprites, or sound.

Each card should have the ability to set its own casting animations. Animations should be separate from card effects, because you may want a different animation for the same effect. For example, consider two cards
- Slap - deal 5 damage
- Headbutt attack - deal 10 damage

Both of these cards have the same underlying effect (a damage effect), but we probably want the casting animations to be different. Because of this, attack animations are assigned in `EffectData`.

Each effect on a card has an associated animation. The animations will play for each effect one by one.

Each animation has an associated delay. This is because we want the effect application to align with a certain point in the animation. For a slap animation, for example, this would be the point when the slap connects with the target.

Set up the cast_animation in the `EffectData.gd`:
```GDscript
# EffectData.gd
@export var cast_animation: PackedScene = null
```
Create a `CastAnimation.gd` that includes a delay:
```GDscript
# CastAnimation.gd
extends Node2D
class_name CastAnimation


signal on_animation_cast_complete

@export var cast_delay: float = 1.0


func play_animation():
   # do whatever animation you want in external nodes or in a child of this script
   
   # Wait for delay to expire. You could override this if you want to do delay in a more sophisticated way.
   await get_tree().create_timer(cast_delay).timeout

   on_animation_cast_complete.emit()
```
Then modify `apply_all_effects` to apply each effect when it receives the delayed signal:
```GDscript
# CardBase.gd
func apply_all_effects():
  var animation_scene = card_effects_data[0].cast_animation
  
  # spawn the animation scene
  var animation: CastAnimation = get_tree().add_child(animation_scene)
  # play animation on CastAnimation.gd node
  animation.play_animation()
  
  # wait for the animation to give the signal for when to play the effect
  await animation.on_animation_cast_complete
  
  card_effects_data[0].apply_effect_data()
  card_effects_data.remove_at(0)

  # apply the next effect in the sequence if there is one
   if card_effects_data.size() > 0:
    apply_all_effects()
```

## Implementation Steps (Optional)

- Create `CastAnimation.gd` and a base `CastAnimation` scene
- Modify `CardBase.gd` to play each effect in sequence
- Add `cast_animation` to `EffectData.gd`
- Create a few sample animation scenes

**Comment by Tysterman74** [comment]
The solution seems pretty straightforward. I feel we can extend this out to just general animations for everything. CastDelay seems specific for the playing of cards, but we can potentially extend this out to a parent class for just delays in general if the need arises.

```
# Animation.gd
extends Node2D
class_name Animation


signal on_animation_complete

@export var delay: float = 1.0
@export var animation_player: AnimationPlayer


func play_animation():
    # Do something with the animation, I haven't looked into AnimationPlayer much with Godot
```
This could potentially open up us being able to implement different animations and if they need to have specific delay or behavior:
```
# CastAnimation.gd
class_name CastAnimation extends Animation

# Override
func play_animation():
    # Do something specific with cast animation
```

```
# EntityAnimation.gd
class_name EntityAnimation extends Animation

# Override
func play_animation():
    # Do something specific with cast animation
```

All just spitballing ideas... your solution is straightforward so we can just roll with yours. I'd figure we start to look towards how other node's and their animation may look like!

**Comment by Tysterman74** [comment]
On top that, I think it'd be good to have some test animations and create new cards to test this Issue out. Slap and Headbutt Attack are perfect cards for this. How were you thinking of going about testing this?

**Comment by cheesefrycook** [comment]
Hm yeah, maybe we could have a common parent for all animations. I haven't thought much about how Entity animations would work, but it will probably be a lot different from how card casting animations work. Maybe for now I'll just do the CardAnimation without the generic parent, but we can keep it in mind for the future!

Definitely would be good to make a few test animations to make sure things work. I can do the Slap and Headbutt Attack like you suggested with some programmer art

**Comment by Tysterman74** [comment]
I'd go forward w/ CardAnimation for now that seems generic enough to work with. Then we can write an issue if we want to try and refactor.
