### ISSUE TITLE
Make stats changes related to character instead of calculating them at attack time

### ISSUE THREAD

**Issue by Turtyo** [Saplings-Projects/1M_sub#4]
**Is your feature request related to a problem? Please describe.**
Currently (as of [this PR](https://github.com/Saplings-Projects/1M_sub/pull/1), the modified stats of a character are calculated inside the attack function by returning a modified version of the stats. This doesn't feel right for several reasons:
- Stats are calculated inside HealthComponent.gd which is an unusual place to find it.
- Stats are calculated by a function which is here to deal damage to characters, this is not a good place for it.
- Stats are calculated by returning a copy of the stats to not modify them. This is the only variable that is not modified and a copy of it is made instead.

**Describe the solution you'd like**
It would be good to have the stats change be calculated in StatsComponent.gd instead of HealthComponent.gd
This implementation would have buffs with an `on_application` and a `on_removal`, which would trigger the modification of stats once a buff is applied or expires.

**Additional context**
Discussed in [this comment](https://github.com/Saplings-Projects/1M_sub/pull/1#discussion_r1412389425)

**Comment by cheesefrycook** [comment]
Makes sense. Might change with #7 though

**Comment by Turtyo** [comment]
Well even if we change the structure, the buffs won't be applied by the attack anyway. But indeed, it might be better to wait for #7 in order to not modify the same at the same time with two different issues.
