### ISSUE TITLE
Proper targeting system

### ISSUE THREAD

**Issue by Turtyo** [Saplings-Projects/1M_sub#42]
## Feature Description

A way for a card to simply add targets to its effects.

## Motivation

Currently we can basically do the following targeting: self, target one enemy, all members of a party and everyone. The problem with the current implementation is that it would require to modify the battler / the card base or effect every time we want to introduce a new way of targeting enemies, because there is no structure that delegates the task to a function made for it.

## Acceptance Criteria

- The new targeting still makes use of the insta-cast defined in PR #39 
- The targeting functions can be added as an element of the data of an effect
- In the battler, the targeting is given to a function so that we don't need to modify the battler every time
- The targeting makes use of the new EnemyManager (similar to PlayerManager) that is done in this PR too

## Proposed Solution

We make a class (let's say `TargetingBase`). We then define sub-class which are all different targeting (like solo-target, all-enemies, targeted enemy + the one on its right, random targeting of X enemies, etc...).

The base has a targeting type (to be able to work with the insta-cast), set to targeting by default but can be overridden by children class that can be insta-cast (like targeting self or targeting all enemies). It also has a blank `generate_target_list` function (name can be discussed ofc); which is overridden by children class

`EffectData` now has a new export variable which is the targeting chosen for the effect we want to apply (so with that you can apply the same effect but in different ways, like poison all or poison target both use the poison effect but with different targeting).

## Additional Context

This is a WIP because it needs #39 to be merged before anyway, and it also seems to be a point that could be open to discussion depending on how the team wants to do this.

**Comment by cheesefrycook** [comment]
Yeah I think it makes sense to add the targeting as new data to `EffectData`. I suppose we will need a global way to access all enemies for the insta-cast cards, because right now the only easy way to get all the enemies is by using `get_party_component` on an input enemy. Perhaps we can add a new `EnemyManager` similar to `PlayerManager` that holds a list of all the enemies, or we can make the Battler's `enemy_list` globally accessible

**Comment by Turtyo** [comment]
I think an `EnemyManager` makes sense, as it will also help us with the enemy tun probably.

**Comment by Turtyo** [comment]
@cheesefrycook if you feel like the explanation and the proposed solution is good, could you confirm this issue ?

**Comment by Turtyo** [comment]
@cheesefrycook should I make the enemy manager in this PR ? or we do it in another PR ?

**Comment by cheesefrycook** [comment]
I think we can go ahead and add it here.

**Comment by Turtyo** [comment]
Actually do we even need an `EnemyManager` ? The list of enemies is already in the battler I think

**Comment by cheesefrycook** [comment]
Yeah that's why I suggested above making the Battler globally accessible. Maybe we can make a `BattleManager` that functions kind of like `CardManager` and `PlayerManager`, where it holds a reference to the current `Battler`. That way, we can access all the enemies from anywhere by calling `BattleManager.battler.enemy_list`

**Comment by Turtyo** [comment]
mmh but if we do that, it's better to directly have an `EnemyManager` and the battler goes to search for that, aswell as the targeting

**Comment by cheesefrycook** [comment]
So the Battler would directly set a separate EnemyManager.enemy_list?

**Comment by Turtyo** [comment]
For now I did this (I didn't start a PR yet):
`EnemyManager.gd`
```GDScript
extends Node
## Globally accessible for easy access to the enemies
## They are for now only accessible through the battler which is not very practical

var enemy_list: Array[Entity]:
    set(list):
        enemy_list = list
```
`Battler.gd`
```GDScript
func _ready() -> void:
	_summon_enemies()
	EnemyManager.enemy_list = _enemy_list
```
so basically `EnemyManager` is just copying from the battler for now

**Comment by cheesefrycook** [comment]
That's fine I think, we will just have to remember to delete from both lists whenever #35 is implemented

**Comment by Turtyo** [comment]
It's the same list, if you delete from one, it should probably delete from the other ? I'm not sure actually, maybe the object inside the array will be deleted, but the array will stay the same. i wonder if there is a way to update the `EnemyManager` every time the list is updated in the `Battler` (a dynamic link kinda ?) . I know we could use a signal, but I'm wondering if it's possible directly

**Comment by cheesefrycook** [comment]
Ah that's a good point. I know that's how it works for Resources - like if you assign a Resource in one place and delete it then all references are deleted. Not sure if works like that for arrays though, would need to test.

**Comment by Turtyo** [comment]
I doubt it works that way for arrays tbh
