### ISSUE TITLE
Remove the `DealDamageData`

### ISSUE THREAD

**Issue by Turtyo** [Saplings-Projects/1M_sub#44]
## Is your amelioration related to a problem? Please describe.

With the changes brought by #43 the role that `DealDamageData` had (ie registering caster and such for stats effects) is not needed anymore. Thus, `DealDamageData` is now just an unnecessary complexity added to the code and it should be removed.

## Describe the solution you'd like
Remove references to `DealDamageData` in all files and use the alternatives instead.

## Additional context
#43 needs to be closed first

**Comment by Tysterman74** [comment]
Current Usages of DealDamageData
![image](https://github.com/Saplings-Projects/1M_sub/assets/5923102/28f58fd4-06fd-49f2-94c4-ebc5022b0d58)

For EffectDamageAll.gd, EffectDamage.gd, Card_DamageHealth.gd we have a reference to the caster and target entity so we can apply the damage directly to those objects.

For Debuff_Poison.gd, it is a child of DebuffBase.gd which is a child of StatusBase which has a reference to the `status_owner: Entity` and `status_applier: Entity` so we can also apply the damage directly to the objects.

**Comment by Turtyo** [comment]
I think you still need to `init_status` for `Debuff_Poison` if you do it manually
