### ISSUE TITLE
Keeping informations related to the player between fights

### ISSUE THREAD

**Issue by Turtyo** [Saplings-Projects/1M_sub#45]
## Is your amelioration related to a problem? Please describe.

Some data currently attached to entities is supposed to be carried between fights (like stats with permanent modifications, or HP). Since the `Entity` object is destroyed at the end of the combat, this information is not kept around.

## Describe the solution you'd like
Have a reference in the `PlayerManager` (that says around between combats if i'm not mistaken ?) to stats that are to be kept.
We can have a `PlayerHP` variable and a `PlayerStats` variables. Once the combat ends, the values of the entity are copied there before the entity is destroyed.
When entering the next room, if we spawn a player entity, the data is copied from the `PlayerManager`. 

## Describe alternatives you've considered
An alternative would be to reword the entire system to move all this system in the `PlayerManager` directly, but that seems like it would be a bigger rework for not much. Since the global structure is already done, there would be a lot references to change probably

## Additional context
This can be started before #43 is done, but it can't be closed before as it will need to reference Stats anyway

**Comment by Tysterman74** [comment]
I wonder if this can be an introduction to a basic save functionality. We can save the player stats to some external file then just read from it and populate the PlayerManager with those suggested changes you mentioned.

**Comment by Turtyo** [comment]
Mmh, I think we should do the player manager first before wanting to do a save system.
The save system would not only need to keep the HP and stats from the player manager, but it would also need item list, card list, torches positions on the map and player position.

The save system is something bigger than just the player manager whose only goal is to enable the player to keep things between fights in the same play session. And directly going to save all this data externally just to load it back at each combat just doesn't sit right to me. Like yes sure, the computer can do it fast you won't even notice, but it seems rather inefficient anyway.

**Comment by cheesefrycook** [comment]
That's a good point, we will want to start figuring out some save/load functionality for all the data we're storing in global AutoLoads PlayerManager, CardManager, MapManager. But I agree that we shouldn't be saving and loading data during a run, seems a bit strange.

For a save system, I think it makes sense to export all the relevant data from each manager to an external file whenever you quit the game, then reload the data from the external file into each manager when the run is started again.

Maybe it'd be good to start an issue related to saving/loading soon. I've found that it's way easier to get the save system done early

**Comment by Turtyo** [comment]
Yes, getting the data of each manager into an external file seems good. The only thing with that is that you wouldn't be able to save mid fight / mid event (probably ?)
I will open an issue for the load/save.

Coming back to this issue, how do we do it ? I've proposed solutions, what are your opinions on this ?

**Comment by cheesefrycook** [comment]
Your solution sounds good to me!

**Comment by Tysterman74** [comment]
If we have the Managers part of the Autoloader, my theory is that the data will persist throughout the session. If that's the case, I say we start utilizing the different Managers to start holding data in-between sessions. 

In order to test this properly, we should have a test button that would instantiate another battle and see if the Player HP persist over.

What else are we thinking of persisting between fights? Buffs/Debuffs?

**Comment by Turtyo** [comment]
When you say "in-between sessions", do you mean keeping data if the player leaves the game and comes back later ? If that's the case, it wouldn't work because variables would get cleared anyway

I think between the fights we should keep:
- HP
- permanent stats (temp stats are reset at combat end anyway)
- any permanent buff
- items (even though we don't have anything of the sort for now
- gold
- number of torches ? that would count as item I guess

Is there anything else ?

**Comment by Turtyo** [comment]
I ended finding this in the docs (which I was already using but it has a part for global variables that i didn't read):
https://docs.godotengine.org/en/stable/tutorials/scripting/singletons_autoload.html

From that link
"
Godot's scene system, while powerful and flexible, has a drawback: there is no method for storing information (e.g. a player's score or inventory) that is needed by more than one scene.

It's possible to address this with some workarounds, but they come with their own limitations:
- You can use a "master" scene that loads and unloads other scenes as its children. However, this means you can no longer run those scenes individually and expect them to work correctly.
- Information can be stored to disk in user:// and then loaded by scenes that require it, but frequently saving and loading data is cumbersome and may be slow.

"

**Comment by Turtyo** [comment]
@cheesefrycook so we do this with auto-loaded singleton right ?

**Comment by cheesefrycook** [comment]
Yes
