### ISSUE TITLE
Map display

### ISSUE THREAD

**Issue by Turtyo** [Saplings-Projects/1M_sub#46]
## Feature Description

A visual representation of the map.

## Motivation

We have the data structure of the map thanks to #30 but we don't have a display for it. The goal here would be to have a simple visual representation of the map. It doesn't need to be fancy, just some squares and letters for rooms events will do as placeholders, but it is to have the base structure of the map display laid out before making it look good.

## Concept art / Designs

![map_concept](https://github.com/Saplings-Projects/1M_sub/assets/49365680/1bc3ff99-e49c-412e-9862-1abd3a70717b)

## Acceptance Criteria

- The map is faithful to the data structure
- No hard coded display, it needs to adapt depending on map that is given
- Player can move on the map by clicking (though this might be done later since we don't really have anything to tell where the player is on the map right now)

## Proposed Solution

No specific solution, make use of Godot's tool !

## Additional Context

This might need the PR that will come from #9 if we want to implement a you see/ you don't see the rooms on the display.

**Comment by Tysterman74** [comment]
Did we ever merge `map-implementation` back down to `main`? I think we may want to make that magic happen first before we start any progress on this Issue.

**Comment by Tysterman74** [comment]
In terms of the UI, were we thinking something similar to StS where we have the icon in the top right 
![image](https://github.com/Saplings-Projects/1M_sub/assets/5923102/93439aea-775d-4758-abe1-185ee06e910f)

Where when we click it, it will open up the map full screen?
![image](https://github.com/Saplings-Projects/1M_sub/assets/5923102/874126e4-ed7b-4125-b2b0-528ffade382c)

**Comment by Turtyo** [comment]
Seems good to me.
And no we haven't merged the `map-implementation` into the `main` yet, for the simple reason that the main doesn't need the map for now. If we merge now and change things later, that's more merge conflicts to solve potentially.

**Comment by Tysterman74** [comment]
From our discussions we had @Turtyo are we okay with leaving the light mechanics out of this issue for now and just focus on getting a display for the map? Then we can save the overlaying of the light in #9?

**Comment by Turtyo** [comment]
Yes, for now we just focus on showing a basic map. The light mechanic can wait for #9 to be implemented. The display may be done at the same time as #9 or separately, but for now we should focus on having a basis before adding more stuff to it.
