### ISSUE TITLE
Save system

### ISSUE THREAD

**Issue by Turtyo** [Saplings-Projects/1M_sub#48]
## Feature Description

Let's be merciful to the player and not force them to win the game in a single play session ! Let's make a save system !

## Motivation

No data is being stored currently anywhere, this save system would help with that.

## Acceptance Criteria

- All relevant data is being stored in an external file
- This file is auto-loaded at game start if it exists
- Auto-save between each room ?

## Proposed Solution

We have different managers, we save the data from all those managers (for example we save the player HP and stats from the `PlayerManager`). Later on we will probably have more managers, like a map manager, we will add those to the save too.

## Additional Context

This system would need to be updated every time a change is made to the available info in the managers, or if a new manager appears.

**Comment by cheesefrycook** [comment]
This seems good, I think autosaving between each room is a good idea. 

Personally I think we should not save progress during an encounter. If you quit the game in the middle of a fight, the fight will restart when you re-enter the game. This is so we don’t have to save all the enemy data too. 

Only problem is the player could quit the fight if they’re about to die. But we could potentially save the player data when the game is closed so there’s no benefit to doing that

**Comment by Turtyo** [comment]
Well if they want to save scum, so be it...
Question for the auto-save, when do we do it ?
For now, we probably auto-save after combat end (so we need #35 probably).
But ultimately, when would we save when we implement the map, we can:
- save when the player does a click to go to the next room
- save when event in current room is done but player has not chosen next room yet
- save when player enters the next room (which could be equivalent to the first option, but with option 1 you could potentially reload when entering a random event to get another random event)

If we do it with an auto-save, do we even provide a save button ?

**Comment by cheesefrycook** [comment]
I'd say we save both when:
- The player first enters an event
- The player enters the map screen

So this means the player could quit the game if they're in an event or on the map screen. For this, we will have to save where the player was when they quit the game (either map or event) so we can reload that scene when the game is opened again.

If the player quits in the middle of an event, then data from that event will not be saved. The event will be restarted when the game is opened again.

If we have auto-save then a save button isn't needed I think.

**Comment by Turtyo** [comment]
The map screen would after the reward screen right ?

**Comment by cheesefrycook** [comment]
Yeah that's what I was thinking

**Comment by Turtyo** [comment]
Did you see the comment I left in #45 about using auto-loaded singleton to hold user data instead of having a main scene load all the other scenes ? I think it might be a better approach to the problem actually, as the Godot doc also says it is preferable to do this way.
When using a main scene to load the other "this means you can no longer run those scenes individually and expect them to work correctly." which could be detrimental to the test structure overall, and would also make debugging harder imo

**Comment by cheesefrycook** [comment]
Yeah, that’s the plan with the Manager system. Each of our managers is an auto loaded singleton. Each of those singletons will hold the save data

**Comment by Turtyo** [comment]
Oh I thought the manager system was a node system that are roots of each scene
Like you have the BattleManager that spawns every time you start a battle. Wasn't that the first thing that was planned ?

**Comment by cheesefrycook** [comment]
Do you mean the Battler? Or do you mean we should add a new BattleManager?

**Comment by Turtyo** [comment]
I think i was being confused thinking we would have a BattleManager, a MapManager etc... being nodes that are called by a higher Manager to spawn them
But that's not the right thing to do, good that we agree on auto-loaded singletons

**Comment by cheesefrycook** [comment]
Yeah, the singleton method should work well I think. The only ones I can think of right now are CardManager, PlayerManager, and MapManager, but there may be more later. I'm thinking we could combine this issue with #45 in a single PR, but maybe it'd be good to wait for #35 first

**Comment by Turtyo** [comment]
Mmmh we could combine with #45 though as I said, this is a bit different I feel like. #45 will start to implement using singleton to carry information between fights, whereas this PR will save that to an external file and load them also
We can probably start #45 before #35 since the things like player health don't need combat end to be stored globally anyway (updated during combat)

**Comment by cheesefrycook** [comment]
I agree they are a bit different, but I figured they're similar enough to combine in one PR. But we can split them up if we think that's more clear.

As far as starting #45 before #35, I'm not sure how we would properly test it if we don't have a way of finishing combat and loading a new scene

**Comment by Turtyo** [comment]
We can start #45 before #35 but #45 will need #35 to be finished to also be able to test itself properly. So yes, you need #35 but you don't need it right away for the structure in itself. Since we can update during the fight, we can first start to test that it works properly during combat, as well as write a setup function for when the fight starts (which can be tested with different starting values).
The final test is with a proper combat end, but in the meantime other things can be done in #45 to prepare for that.

**Comment by cheesefrycook** [comment]
Yeah true. I'm going to get started on #45 then

**Comment by BishopJohnson** [comment]
Would it be alright for me to pick up this issue?

**Comment by Turtyo** [comment]
Cheesy is already assigned to the issue, so it would be better to not be two on this. However if Cheesy doesn't have the time currently and agrees to let you take it from where he left it, then sure

**Comment by Turtyo** [comment]
Cheesy is not available currently to work on this so this issue can be taken by someone else again. @BishopJohnson you mentioned wanting to take this, but since you are working on something else currently someone else might take it first (i might, if I don't take another issue like better map generation)

In any case, since things changed quite a bit since this issue was opened, I think it will be good to discuss it again, so I'm removing the confirmed tag

**Comment by Tysterman74** [comment]
To sum up what has been discussed so far, we want to auto-save for the following scenarios:
- The player first enters an event
- The player enters the map screen

With NO manual save.

As for what we want to save are the following:

- PlayerManager (position, initial_position_set, map_movement_allowed)
- InventoryManager (gold, torch, consumable and relic component)
- XpManager (only the current_xp as everything else can be deduced from that)
- SceneManager (only the current scene)
- MapManager
- CardManager (only the current deck)

**Comment by Turtyo** [comment]
Those information need to be written on an external file (following the example of the doc I think)
We might add a manual save (to quit in the middle of a fight) but that's not the plan right, so no manual save

I think you will also need to add a "continue" button in the menu, it will be moved later once Paper finished the issue about the menu design

**Comment by Tysterman74** [comment]
> I think you will also need to add a "continue" button in the menu, it will be moved later once Paper finished the issue about the menu design

If Paper is working on the Continue button, I'll just have a temp button on the menu for now and will merge in their changes when that PR is done.

I'll go ahead and start on save for now.

**Comment by Turtyo** [comment]
Makes sense ! Linking a button isn't difficult after all, if all the background is done
You can probably add a temporary button for testing purpose
