### ISSUE TITLE
Should `Core/Enums.gd` be moved to `Global/GLOBAL_VAR.gd` ?

### ISSUE THREAD

**Issue by Turtyo** [Saplings-Projects/1M_sub#54]
## Is your amelioration related to a problem? Please describe.

There are enums in both files, and that's pretty confused.

## Describe the solution you'd like
Move one file into another. I would at least like everything to be in `Global` though.

**Comment by cheesefrycook** [comment]
I personally like having all enums in the separate enum file, because if you want to use an enum you know you can just use `Enums.whatever`. Maybe we could reserve GLOBAL_VAR for non enums?

**Comment by cheesefrycook** [comment]
Yeah that sounds good!

**Comment by Turtyo** [comment]
Do you agree on renaming `Enums` and if yes do you have any proposition ?

**Comment by cheesefrycook** [comment]
`GlobalEnum` maybe? I like `Enums` more personally though because it's shorter to write.

**Comment by Turtyo** [comment]
I don't want to confuse it with the keyword `enum`
