### ISSUE TITLE
Energy system

### ISSUE THREAD

**Issue by Turtyo** [Saplings-Projects/1M_sub#56]
## Feature Description

The energy system is the cost associated to playing cards.

## Motivation

The player has a limited amount of energy and each card costs some. This naturally limits the amount of cards that can be played in a turn, which is usually a good thing to not have players be gods on each run :laughing: 

## Concept art / Designs

The chosen design is to have players start the combat with less energy than the max (3/4 for example). Each turn, they gain 3 energy, with a total energy capped at 4. Energy carries between turns, but since it's a 3 per turn and 4 max, you can technically only carry 1 energy to the next turn. 
Of course, the numbers are given as example we should be able to edit them if we want. Note that by generating energy, the player can temporarily have more energy than the max during a turn (but the energy will go back to the max at the start of the next turn if they have more than the max).

## Acceptance Criteria

- The generation and max energy works as intended
- Each card now has an associated cost
- We should have a way to ignore the energy cost for testing purpose (if we want to play a lot of cards in a turn as devs)

## Proposed Solution

Make a class for the energy. There we define the useful functions such as calculate the energy of the player at the start of the turn, remove energy from the player when a card is played, add energy etc...
Each card now has a cost associated (should it be an instance of the energy class or a simple int ?)
The player also now has an energy attribute. They can't play cards if their energy is lower than the cost of the card (they should probably not be able to even put the card in targeting position for the cards that need a target, so it's not confusing).
The logic of a card now should include a call to reduce the energy of the player given the cost of the card.

For the devs, a way to be able to play a lot of cards in a single turn would probably be to just give a lot of energy (so the system is still running, just that if we have 1000 energy we won't run out). That might be done with a parameter in a global file ? Sure the player could go and cheat to give themselves unlimited energy too, but the code is public anyway so if they want to, then they can.

## Additional Context

Should this be broken down in a few smaller PR ? Maybe a first one for the energy system in itself with the functions and adding that to the player, then the implementation for the cards ? It's not impossible to do everything in a single PR, but it would be big.

**Comment by cheesefrycook** [comment]
I think we should add a new `EnergyComponent` similar to `HealthComponent` that is only on the player entity. Then of course add an accessor function on the Player class like `get_energy_component`. For the energy itself, I feel like we can do a simple int. I'm not sure if we will need any more information in that regard. A single PR for both cards and player is fine I think.

For the unlimited energy cheat, I wonder if it makes sense to have some sort of global file that controls cheat values. Could have stuff like `unlimited_energy` or `take_no_damage`. In the non-editor version of the game, the cheats would be ignored. That's probably best handled in a separate PR though. If we want to add unlimited energy in a quick way, we could just do a bool on `EnergyComponent` for `unlimited_energy`

**Comment by Turtyo** [comment]
The reason for having an actual class for the energy is for typing reasons. And also in case we do need more information on the energy

Yes we can make a cheat file to put every modification that is dev related and not intended for the actual game. We could also have cards that are dev related put in a separate directory (like the card that deals damage equal to health lost, which is totally OP and should not be used for the actual game). How do we check if the game is in the editor version or the exported version though ? We might indeed be better of by doing that in a separate PR.

**Comment by cheesefrycook** [comment]
I guess for typing it's a bit more clear than an int. So i'd be something like 
```GDScript
extends Resource
class_name Energy

var energy: int = 0
```

**Comment by Turtyo** [comment]
Will check that for the editor version !
Yes I was thinking something like that, though using `energy` for the actual amount and `Energy` for the class might be confusing (like confusing the class with its variable). Maybe `EnergyBase` to follow other conventions ?

**Comment by cheesefrycook** [comment]
Sounds good to me

**Comment by Turtyo** [comment]
@cheesefrycook are we all good on explanations ? if so, can you add the confirmed tag ?
