### ISSUE TITLE
Move all art images into a dedicated folder

### ISSUE THREAD

**Issue by Turtyo** [Saplings-Projects/1M_sub#57]
## Is your amelioration related to a problem? Please describe.

The `Card` folder is starting to get a bit disorganized because of the images for the cards being in the Card folder

## Describe the solution you'd like
Move all the images inside a `card_images` folder inside the `Card` directory

## Additional context
I was about to do that on my current targeting PR but I thought it might be better as a small PR of its own because people that merge this small PR will have to tinker with their imports and .tscn files that reference those images.

## Edit : proposed solution after discussion
```
Root/
    | - - Art/
	  | - - Background
	  | - - Cards
	  | - - Characters
	  | - - Enemies
	  | - - Items
	  | - - Menus
	  | - - NPC
```
All arts within an art folder

With naming convention:
- all names start with art-<something> with the something being:
    - background : `bg-<area_number>-<number>`
    - NPC :` npc-<name>` ; name should be written using underscore if there are spaces
    - Mob :`enemy-<name>-<pose>` with pose being the name of a particular pose the enemy can have (defeated, full life, took damage, etc...)
    - Items : `item-<type>-<name>` with type being either accessory or consumable
    - Cards : `card-<name>`
    - Character : `player-<pose>`
    - Menus : `menu-<name>-<number>`

Tests should be added to ensure that the naming convention is respected.

**Comment by Tysterman74** [comment]
Do we want to enforce a naming convention for the card images while we're at it as well?

**Comment by Turtyo** [comment]
Instead of just doing this for cards, let's make an `Art` folder at the root of the project, with all the art we will use in the game.
It could have a structure like follows:
```
Root/
	| - - Art/
		| - - Background
		| - - Cards
		| - - Characters
		| - - Enemies
		| - - Items
		| - - Menus
		| - - NPC
```
What do you think @Tysterman74 ?

**Comment by Tysterman74** [comment]
Oh heck yeah that's even better. I'm thinking we can leave a .txt file in that folder as well for naming convention for all the different files?

**Comment by Turtyo** [comment]
good idea for the .txt

**Comment by Turtyo** [comment]
I was even thinking of a little python script that checks that naming conventions are respected based on the `.txt`

**Comment by Tysterman74** [comment]
Could be possible with GDscript. Honestly I think it can be possible with using GUT and the base assert functions too have it as an actual unit test.

**Comment by Turtyo** [comment]
Ah yes that might work as a GUT test indeed, just go through all the files and check the formatting based on file type

**Comment by Turtyo** [comment]
Actually before anyone starts on this issue, we should decide on the naming convention, my idea:
- all names start with art-<something> with the something being:
    - background : `bg-<area_number>-<number>`
    - NPC :` npc-<name>` ; name should be written using underscore if there are spaces
    - Mob :`enemy-<name>-<pose>` with pose being the name of a particular pose the enemy can have (defeated, full life, took damage, etc...)
    - Items : `item-<type>-<name>` with type being either accessory or consumable
    - Cards : `card-<name>`
    - Character : `player-<pose>`
    - Menus : `menu-<name>-<number>`
 
File type should support transparency, so something like png

**Comment by Tysterman74** [comment]
Ya this is a good base convention! I'm not sure how animations work with Godot, but if we need to keep separate images for the key frames, then we can easily append the image names w/ `-[frame-number]` but I think a spritesheet should also do the trick. If we want to also add some unit tests for checking naming convention we should add it on to the issue at the top, otherwise I think it's just extra credit at this point.

**Comment by Turtyo** [comment]
I edited the original message to add what we discussed. I tested, we shouldn't need key frames as videos are supported, and we need to chroma key videos because alpha is not really supported in videos as is
