### ISSUE TITLE
Map implementation

### ISSUE THREAD

**Issue by Turtyo** [Saplings-Projects/1M_sub#6]
## Feature Description

A map composed of different floors, each floor composed of different rooms. After each combat you open the map and choose your next destination on the floor above you.
Each room has an icon depending on the encounter. The player can move to the room directly above them or the ones on the side of the room directly above them.
The entire map shouldn't be visible, and should interact with torch placement, cf #9

## Motivation

Since we are making a dungeon crawler, we have decided on using a map with floors and nodes (which we will probably need to name "rooms" or something else to not get confused with Godot nodes). This issue is meant to discuss the implementation of such a map system.

## Concept art / Designs

![floor_concept](https://github.com/Saplings-Projects/1M_sub/assets/49365680/28c91478-a888-4f67-a6e7-2f54025cc472)

## Acceptance Criteria

- Map should only be used once after each room.
- Movements on the map must make the player go up one floor (no movement on the same floor or to a floor below).
- You can toggle viewing the map (if you have something else you to check first this can be useful)
- Map should have icons on each room depending on the room type
- Each room can have its event changed depending on light level (cf #10 )
- The map should have an indicator of the rooms the player can access from their current position
- The entire game can be composed of several maps (sections), where you access next section after beating the current section's boss
- Map should be interacted with via the mouse (open to discussion)

## Proposed Solution

The most basic element should be the `Room`. Then we have `Floor` that are composed of rooms and finally the `Map` is composed of floors.
When the player starts a new map, an algorithm makes a distribution of the rooms, starting with the most influential events such as mini-boss and shops / heal points, then fills the remaining rooms with mobs / mystery events (or even other types of events depending on if we add more).
The indicator of the rooms that are accessible could be a having the border of the rooms glow.

A `Room` should have variables to do:
- associated event (and thus we need to create an "event" class)
- light level and a function to calculate the light level
- a boolean to know if we show the tile or not. This could also be directly linked to the light level to have non-visible, dimly lit, lit, brightly lit which appear differently

Cf #10 for the discussion on `Room`.

Floors are a collection of rooms. Not sure of the date structure to use here. We need the floor to ensure that movements are made only from one floor to the one above

Map can be an array of floors.

Other possibility instead of having floors and map class is to have the `Map` be a `2D Array` of rooms, which might facilitate the manipulation of said object.

## Implementation Steps

We should first focus on implementing the structure of the map, then:
- how to move between the rooms and indicator
- create the `Event` class [ #20  ]
- algorithm for the distribution of events
- light level management

## Additional Context

Since this is a big feature, a new branch for this specific feature will be opened, so that multiple people can work on it; before merging it back to the main. The pull requests in link with this issue will be done with the `map_implementation` branch (which will be created as soon as the first pull request is closed).

Any help in this discussion is appreciated, as some points do indeed need discussion.

**Comment by Turtyo** [comment]
@multi-arm Since I see you self-assigned, what do you think of the possibilities of structures i talked about ? After thinking about it, I think a 2D array will probably work better (though a list of list is kinda the same thing, but we have associated functions with arrays)

**Comment by multi-arm** [comment]
hi sorry for the late reply, i think 2d arrays work well for this, i just need to wrap my head around it first. also, how will the event class work for rooms? i saw that it was saved for a different issue, i just don't know if the issue will be for map generation or something else.

**Comment by Turtyo** [comment]
I agree about the array, I think it would work better. Having a floor class would have been good if you could make actions / move on a floor, but since each turn you move up it doesn't really make sense.

The `Event` class is a way to store the encounter in a given room. Basically, it's our way of saying "there is an enemy encounter in this room, the enemies are those enemies" etc...

**Comment by Turtyo** [comment]
Something you can see on the image but that has really been mentioned: Map shape
A few rules for the map:
- Each floor can only be 2 larger, same size or 2 smaller than the previous floor (this ensures that every room is accessible from the previous floor and that the map keeps its shape)
- The size of a floor is an odd number
- There is probably another rule about the end of a map to make sure it finishes properly but i need to think about it a bit more

**Comment by Turtyo** [comment]
Removing the milestone because there might be more stuff to do than just the bare minimum on the map (like movement animation, adding art, etc...)

**Comment by Turtyo** [comment]
Will be closed once #77 is merged.
