### ISSUE TITLE
Remove unused function parameters / variables and add missing typing

### ISSUE THREAD

**Issue by Turtyo** [Saplings-Projects/1M_sub#65]
## Is your amelioration related to a problem? Please describe.

There are a lot of unused function parameters in the code (I count 7), which produces warning messages that could be avoided.
There are also quite a lot of untyped variables or functions with no return type.

## Describe the solution you'd like
Either remove the function parameter / variable if you can, or put a `@warning_ignore("unused_parameter")` before the function (only if you are overriding a function or using a built-in, which forces you to have the same signature even if you don't use all the variables).
For the untyped variables, type them properly.

## Additional context
Here is a list of all the places i found with such a problem:
- `res://Cards/CardContainer.gd`
    - `func finish_active_card_action(card: CardBase) -> void:`
    - `var move_state: Enums.CardMovementState = movement_component.current_move_state` in `func _update_card_positions() -> void:`
- `res://Cards/Movement State/CardMovementState.gd`
    - `func on_state_process(delta: float) -> void:`
    - `func can_transition_from(new_state: Enums.CardMovementState) -> bool:`
- `res://Cards/Movement State/MoveState_Discarding.gd`
    - `func can_transition_from(new_state: Enums.CardMovementState) -> bool:`
- `res://Cards/CardMovementComponent.gd`
    - `func _process(delta: float) -> void:`
- `res://UI/EndTurnButton.gd`
    - `func _process(delta: float) -> void:`

There are a lot of untyped variables so i'm not gonna list all of them

To see all of that, you can go into Project -> Project Settings, activate Advanced Settings then go to Debug -> GDScript and activate `Untyped declaration`, `Unsafe cast` as a warn. `Unused variable` and `Unused parameter` are already set to warn by default.. I think all of those options should be set as an error after the PR related to this issue. Warn can be ignored so we could potentially introduce new untyped declarations or unused variables. If we set it as an error, it won't be possible to ignore it.

**Comment by Tomzkk** [comment]
If unused parameters are set to be an error, can they still be made an exception using @warning_ignore ? Since like you mentioned there are cases like overriding functions etc where we might be forced to have some extra parameters

Similarly, is there a way to make an exception for untyped declaration ? There are cases like for example in [test_death_handling function](https://github.com/Saplings-Projects/1M_sub/blob/11d321539ea9176f40899de5f6cf5d8257d8e081/Tests/test_death_handling.gd#L16), where we may pass a node that has already been freed into it and so we can't set a type for the parameter.

**Comment by Turtyo** [comment]
I tested, it seems like you can use `@warning_ignore("unused_parameter")` even to ignore errors. 
You can use `@warning_ignore("untyped_declaration")` for untyped stuff like the node example you gave.
I got a lot of errors an unloaded file when I put everything in error, so i only tested this on one file and it seemed to make the error disappear. The only way to be sure will be once this issue is solved though.
