### ISSUE TITLE
Movement on the map

### ISSUE THREAD

**Issue by Turtyo** [Saplings-Projects/1M_sub#67]
## Feature Description

Be able to move on the map by clicking the display on the map.

## Motivation

Now that we have a map display to go with our map structure, we need the player to be able to move between the rooms in order to have a progression in the game

## Concept art / Designs

I'm thinking of having the room have a border that lights up a bit when you hover it to make it clear where you are going.

## Acceptance Criteria

- Player can only move to the room directly above, up-left or up-right (they can't jump a floor, they can't move in the same floor either)
- A little icon to show in which room the player is currently

## Proposed Solution

I'm thinking that add buttons in the map display. For now I think we are just displaying an image for each room (you confirm @Tysterman74 ?), so in the loop that's building the position of each image, we also put a button with the same dimensions as the room.

We have two possibilities:
- either we had a button to every room on the map when we display it, and we check when a player clicks if they can access the room from where they are, if so we move them there
- when building the layout of the buttons on top of the map display, we only add the button if the player can access the room

I like option 2 more because it will use less resources and is also probably less error-prone. One point we need to be careful of is to move the buttons when the map is moved by scrolling

We can have a hover state for the map display to highlight the rooms we have the mouse over.

Maybe an even better solution is to directly have room in the map display be a button, so it will always scroll with the map without problem, but i don't know how much we can custom the button to display images.

**Comment by cheesefrycook** [comment]
I agree with option 2. Each of the RoomUI scenes can have a button Control attached to it, then connect that to a ClickHandler. This is pretty much how clicking on cards works. Buttons in Godot you can customize all the different states for it (normal, pressed, hovered, disabled), so it should be pretty flexible for our needs

**Comment by Turtyo** [comment]
I meant customize as in "put an image on the button" to directly make any room a button with an image, instead of an image with a button overlay on it

**Comment by Turtyo** [comment]
I will do this, discussion probably not over but I know I'll do it so I assign myself already

**Comment by Tysterman74** [comment]
![image](https://github.com/Saplings-Projects/1M_sub/assets/5923102/78358873-baf8-438f-a3e3-10e0964934f9)

This is the current implementation on `map-implementation` for the RoomUI. To Cheese's point, we can add the button Control to the RoomUI, but once we generate the MapUI all of the rooms will already have this button created. 

I think the best bet here would just be disabling the button if the room is inaccessible to save the hassle of checking the mouse input.

In terms of the button and an image, Godot does have a `TextureButton` Control Node that has all the features of being able to attach an image and the functionality of a button all in one. This would be good to have so once we have assets for the buttons, we can specify we want these different textures for the buttons.

![image](https://github.com/Saplings-Projects/1M_sub/assets/5923102/bd106f47-ea72-48f8-aa02-2be5ee8c3650)

**Comment by Tysterman74** [comment]
MapUI.gd will have the logic of generating the RoomUI out. If we're gonna use this same scene for both Map viewing during a battle and for navigating between rooms after a battle, we may want to have some sort of state of what the player is currently in so we don't navigating to a room in the middle of a battle.

**Comment by Turtyo** [comment]
a `TextureButton` with a disabled state depending on player position seems like the best bet
I agree with the state. Not that i get why a player would watch the map during the battle, but oh well :shrug: 
we have signals for when a combat is finished / an event is finished. I think the enabled state of the buttons should be activated when the signal is emitted (so players can go to next room), and disabled when players enter a new event (there are signals emitted at the start of combat, but i wonder if those are combat specific or we have something specific to starting whatever event)
If this signal of starting event doesn't exist, i'll just make it

**Comment by Tysterman74** [comment]
I only mention the state, since in StS we're able to check the map while we're in combat even though we can't navigate anywhere haha

Realistically speaking, it does depend on if we want to have the map icon available to players during combat. If that's the case, we should have that state to disable the map buttons.

**Comment by Turtyo** [comment]
Yeah I guess we could leave it available, they might want to check it for reasons. Will just put a state that goes to active when the event ends and disable when the event starts

Seems like the button can also still display the texture even in disabled state, so this should work
