### ISSUE TITLE
Healing with a strength buff will negate the healing

### ISSUE THREAD

**Issue by cheesefrycook** [Saplings-Projects/1M_sub#73]
## Describe the bug
If you use a heal with a strength buff, then the heal will be negated by the amount of strength.

## To Reproduce
1. Apply a Strength +1 card to the player
2. Use a Heal +1 card
3. Observe that the player heals no damage

## Expected behavior
The player should heal 1 damage.

## Additional context
This is because the heal is dealing negative damage to the player, so the strength buff is adding +1 to the -1 heal, which makes the healing equal 0. When applying a strength buff, maybe we ignore if the damage is dealt to the caster?

**Comment by Turtyo** [comment]
Or we should make the heal a special thing of its own
In the facts we will use deal damage with a negative value, but when calculating stuff we base ourselves on a stat of its own
Plus, this will be useful if we have healing buffs

**Comment by Turtyo** [comment]
If using deal damage automatically means this can't work, we just make a new function for heal on its own, though i would rather avoid code repetition, but this is better than giving a boolean to the function to check if we heal, which clearly happens much less often than dealing damage
