### ISSUE TITLE
Global scene loader (map scene loader excluded)

### ISSUE THREAD

**Issue by Turtyo** [Saplings-Projects/1M_sub#74]
## Feature Description

Load a different scene when changing rooms.

## Motivation

The only scene currently in the game is the combat scene and moving on the map doesn't change anything. It would be good to have the associated event with each room be loaded when we go in.
Note that this scene loader should also be able to stuff outside of the events of each room, for example the start menu, the end credits, etc...
This second point is up to discussion, we could decide to have a single loader for all the game, or make a general loader and a another loader for the map in particular

## Acceptance Criteria

- Load the event associated with the room you move into
- Don't allow the player to move to a new room if the event in the current room is not finished
- A DEBUG const to be able to ignore the previous point for devs only (see `DEBUG_VAR.gd` after alpha 1.0)

## Proposed Solution

The scene switcher would be based off of [this example in the Godot documentation](https://docs.godotengine.org/en/stable/tutorials/scripting/singletons_autoload.html#custom-scene-switcher), which uses a singleton as scene loader.

The block of the scene switch can be done using a `is_map_movement_allowed` boolean set to true by default when the game starts. We have a function named `toggle_map_movement`. We make two signals, `event_started` and `event_ended`. We connect `toggle_map_movement`to those signals.
Upon receiving a signal, the toggle function will put the boolean to true if it's false, and false if it's true. When we start, the map movement is set to true and the player can choose a room on the first floor. We enter an event, a signal is emitted, the map movement is not allowed anymore. When the event ends, the end signal is emitted and `is_map_movement_allowed` becomes true again, thus allowing the player to move again.
The DEBUG const can easily be done by having the getter for `is_map_movement_allowed` return `DEBUG_MAP_MOVEMENT_ALLOWED or is_map_movement_allowed`. If the DEBUG is set to true, the getter will always return true since we use a or expression.

## Additional Context

This needs map to be merged into main (so after alpha 1.0)

Edit: This PR will deal with making the main switcher, the map switcher will be done in a later PR

**Comment by Turtyo** [comment]
Considering all the other stuff that needs to have a scene switcher, it would make sense to have this be a global scene switcher, and not just a switcher for the map

**Comment by JonaLam** [comment]
It depends how you intend scene switching to work while in a run. Should we unload the map scene when we enter combat, or de we have it in the background? If we leave it open, then it would be kinda weird to use the same system for the main menues and such, but there are a fair few advantages for keeping the map loaded, like not haveing to load it again, and allowing the player to look at the map mid combat/event.

**Comment by Tysterman74** [comment]
> It depends how you intend scene switching to work while in a run. Should we unload the map scene when we enter combat, or de we have it in the background? If we leave it open, then it would be kinda weird to use the same system for the main menues and such, but there are a fair few advantages for keeping the map loaded, like not haveing to load it again, and allowing the player to look at the map mid combat/event.

If we were to save the map data with our save data functionality, would this make things easier with having to reuse the same system?

**Comment by Tysterman74** [comment]
If the jury is still out on the map scene implementation and generalization, I think we can at least get the scene switching for "Loading", "Main Menu", and "Battle" done first. Once we have that fleshed out we can decide how we want to go about the map scene stuff. At least from reading your write-up on this Turtyo, it essentially feels like two different pieces of work that can be worked on independently.

**Comment by Turtyo** [comment]
> Should we unload the map scene when we enter combat, or de we have it in the background?
@JonaLam 
As it is currently, the map scene spawns from a button within the combat scene. We should have a way to keep this button whatever the scene, so we can always open the map, maybe a container that spawns automatically on every scene ? what do you think @Tysterman74 ?
>  it essentially feels like two different pieces of work that can be worked on independently.
It probably can yes. Since both were scene switchers, I thought maybe doing a single one would be good.
But we can also do them separately, as the map scene switcher would need to do more stuff (like loading events and such), where the general loader would only need to load static scenes (main menu, loading, adventure (which would then be handled by the map scene switcher))
I'm not sure how having two scene switchers might work, but it's probably clearer if they are separated indeed

**Comment by JonaLam** [comment]
### If we were to save the map data with our save data functionality, would this make things easier with having to reuse the same system?

It could definitely be used, but it might be inefficient to have to reload the entire map scene and run the loading syste every time the player wants to look at the map.

**Comment by JonaLam** [comment]
I think it could be a good idea to split them up, as how the scene loading wil work wil probably be diffrent for while in and outside of runs

**Comment by Turtyo** [comment]
Yes, but it also seems inefficient to have two scene loaders
Maybe we should just have a single scene loader (ie a single singleton), but using different context
I feel like having two singleton doing scene loading could lead to unwanted bugs, where it would be much clearer with only having one with different actions depending on the context in which it is used (ie what calls the scene switcher)

My idea would be to implement the global scene switcher first (as this will be a good base, and will be easier to do). Have a a global loading context that does stuff between menus.

Then in another PR, add another context (another set of functions), that trigger in a different context (this can be done by having the buttons of the respective context be connected to their respective loading functions).
The global context would need much less information, whereas the map would need more, this would be reflected in the function.

> It could definitely be used, but it might be inefficient to have to reload the entire map scene and run the loading syste every time the player wants to look at the map.

I think Ty was referencing the external save, which is only used at game loading to keep progress between runs. During the game, the map information is globally loaded in the MapManager and doesn't need to be reloaded every time. The Map Display scene on its end is destroyed and created every time the player clicks on the map button.

**Comment by Tysterman74** [comment]
> Yes, but it also seems inefficient to have two scene loaders Maybe we should just have a single scene loader (ie a single singleton), but using different context I feel like having two singleton doing scene loading could lead to unwanted bugs, where it would be much clearer with only having one with different actions depending on the context in which it is used (ie what calls the scene switcher)
> 
> My idea would be to implement the global scene switcher first (as this will be a good base, and will be easier to do). Have a a global loading context that does stuff between menus.
> 
> Then in another PR, add another context (another set of functions), that trigger in a different context (this can be done by having the buttons of the respective context be connected to their respective loading functions). The global context would need much less information, whereas the map would need more, this would be reflected in the function.

This is a good plan. Start off small with the base then you'll have a better idea of how to handle the map scene afterwards once we have that down.

> As it is currently, the map scene spawns from a button within the combat scene. We should have a way to keep this button whatever the scene, so we can always open the map, maybe a container that spawns automatically on every scene ? what do you think @Tysterman74 ?

My first gut feeling to this would be a container that holds all of the reusable UI elements that we will see in different parts of the gameplay. Maybe a scene that is the container for all reusable UI elements, then inside that container is the scene for whichever flow the player is at currently (battle, map, event, etc.). Does that seem inline with what you're thinking Turtyo?

**Comment by Turtyo** [comment]
Basically an "overlay" scene that we put on every part where we want the same UI elements ?
Not all parts would need that though, the map overlay would only be present during the adventure part for example. But this seems good indeed.
Will just have to see how it plays with the scene switcher, because it would need to swap containers too with that logic
