### ISSUE TITLE
Implementation of the event Dialogue

### ISSUE THREAD

**Issue by Turtyo** [Saplings-Projects/1M_sub#75]
## Feature Description

The event Dialogue is on where the player is faced with a scenario and they have multiple choices to choose from, potentially gaining or losing things from their choices.

## Motivation

This event is important since it makes it so that we don't only have combats, shops and rest in the game.

## Concept art / Designs

An example in Slay the Spire
![image](https://github.com/Saplings-Projects/1M_sub/assets/49365680/d7697a18-aa86-4f79-b62a-9d925b26d050)

An example in Faster Than Light, where you don't have the consequence of each choice written. Result is always the same, but you need to know by playing enough or using your logic
![image](https://github.com/Saplings-Projects/1M_sub/assets/49365680/c80b65da-5a8d-4643-8d7d-e15ad8410b2d)

Note that it doesn't need to look like that, nor do we need to indicate the consequence of each action.

## Acceptance Criteria

[Define the criteria that need to be met for this feature to be considered complete.]

- A text box and multiple choices
- Possibility to have colored text
- Animations can play during the event

## Proposed Solution

I was thinking we could start by using [this nice addon](https://github.com/nathanhoad/godot_dialogue_manager) that already seems to do most of the heavy lifting for the dialogue part.
The image and animation part can be an animation player probably

Edit : using the addon we might have a problem with licenses not being compatible, need to check that first

**Comment by JonaLam** [comment]
The license seemed fine, but someone should also read it as I'm not sure I fully understood it.

**Comment by Turtyo** [comment]
I think each event should have its associated dialogue options. We could have a database (which could just be a singular file with all the possible events and related dialogues), to hold the dialogue linked to each event. This would be loaded upon entering a room with the related event, along all other necessary resources (such as art or music for example, which could also be listed in this event file;
this would allow us to have a standard format for events, which allows us to just have a single scene for events, that loads different data; and not have to do a scene per event (which would quickly start to add up).

I will try to read the license in more details to be sure it's compatible. If it is not, we can check what they did but we won't be able to copy, we will have to do our own stuff basically.

**Comment by Tysterman74** [comment]
Should we potentially talk with art and design on how we want to how the event dialogues UI look like? The add on looks like it has a lot of customization, I think it would be helpful to get a first pass like a wiremock or something of how we want it to look.

> I think each event should have its associated dialogue options. We could have a database (which could just be a singular file with all the possible events and related dialogues), to hold the dialogue linked to each event. This would be loaded upon entering a room with the related event, along all other necessary resources (such as art or music for example, which could also be listed in this event file;
> this would allow us to have a standard format for events, which allows us to just have a single scene for events, that loads different data; and not have to do a scene per event (which would quickly start to add up).

Adding onto this, I think making an ease of use way for the designers to be able to write these events would help with us having to put them all in.

**Comment by Turtyo** [comment]
Honestly we could have all of the data in like a json or a toml file, because this is made for it. Or maybe the addon already uses a certain kind of file format, i don't remember.
We should indeed ask the designers to write the events in a certain pre-determined format if that's what you meant Ty, as this will allow us to not have to reformat everything

**Comment by Turtyo** [comment]
Asked the design team for some UI mockup / concepts so we can go from there on this issue for the visual side.
For the BG handling side, need to look more in depth at this addon I think.

**Comment by Tysterman74** [comment]
> We should indeed ask the designers to write the events in a certain pre-determined format if that's what you meant Ty, as this will allow us to not have to reformat everything

Ya. Essentially my hope is that we provide them the format on how to write these events, they cook up these formats and we can just drop them into the folder.

**Comment by Turtyo** [comment]
That seems the most optimal; we'll probably choose an easy to read format (not JSON, because that's a bit of a headache)

**Comment by Turtyo** [comment]
Ah btw I checked, MIT license is GPL compatible so we can use the addon without problem

**Comment by Tysterman74** [comment]
I saw there were some discussions with design on the layout, but was there a final say on how we want it to look like?

**Comment by Turtyo** [comment]
We haven't voted yet, this will come in the following days

**Comment by Tysterman74** [comment]
Pending discussions on design, I think I can at least start getting the addon implemented in and messing around with it.

**Comment by Turtyo** [comment]
Sure, it won't be time lost if you already have a structure and idea of how this works !
