### ISSUE TITLE
Player can put a torch down while they are not on the map

### ISSUE THREAD

**Issue by Turtyo** [Saplings-Projects/1M_sub#76]
## Describe the bug
The first time the player opens the map they can select a room to go on the first floor. But the add torch part is not disabled, meaning a player can add a torch to the map while not being on the map yet

## To Reproduce
1. Open the map
2. Don't select a room on the map
3. Click on Add Torch on the left
4. Click yes
5. Game freezes, because the player position is not yet set

## Expected behavior
Add torch should not be visible if the player has not gone into a room yet

## Additional context
There will be more changes, later on, with disabling the button if the player doesn't have torches anymore for example. The button shouldn't be invisible then, but should have a different texture when disabled (to show it's there but not available).
It would also be good to have a popup when the button is hovered to show the reason (not enough torches for example).

**Comment by Tysterman74** [comment]
I can take this one. I'll disable it if player position isn't set. I'll see about having a popup show when disabled.

**Comment by Turtyo** [comment]
Seems good to me :+1:
What do you mean about a popup when disabled ?

**Comment by Tysterman74** [comment]
> It would also be good to have a popup when the button is hovered to show the reason (not enough torches for example).

You had this on the issue, I was thinking if we try to tap we show the popup

**Comment by Turtyo** [comment]
Oh yeah, seems like a good idea
The reason should probably be different though than "not enough torches"
We should have a way to have a string message for the popup button to select depending on the reason then
