### ISSUE TITLE
Auto-focus map display on player position

### ISSUE THREAD

**Issue by Turtyo** [Saplings-Projects/1M_sub#78]
## Is your amelioration related to a problem? Please describe.

When opening the map, the view is always at the top. This means that we need to scroll down every time we want to see where we are for most of the map.

## Describe the solution you'd like
When opening the map, the floor the player is on should be visible at the bottom of the screen.

## Additional context
This needs to wait for Alpha 1.0

**Comment by Tysterman74** [comment]
With SmoothScrollContainer, there's a way to scroll to a certain y position. 
```
func scroll_y_to(y_pos: float, duration:float=0.5) -> void:
	if not should_scroll_vertical(): return
	velocity.y = 0.0
	y_pos = clampf(y_pos, self.size.y-content_node.size.y, 0.0)
	var tween = create_tween()
	var tweener = tween.tween_property(self, "pos:y", y_pos, duration)
	tweener.set_ease(Tween.EASE_OUT).set_trans(Tween.TRANS_QUINT)
```

Within MapUI.gd, when figuring out rooms we can check where Fauna is set and the Y-position then call `scroll_y_to()` to the Y-position.

**Comment by Turtyo** [comment]
Yes the y position should be easy to calculate as a roomUI size * floor number (plus maybe an offset due to the distance between floors)
I think it should auto-focus on the position of the player in a way where we can see from the previous floor.
Also when going towards the end of the map, the set position shouldn't make it so that we start seeing grey areas (meaning if the set position would make the border of the view higher than the border of the map, it should just open normally showing the top of the map)
