### ISSUE TITLE
Game splash art loading

### ISSUE THREAD

**Issue by Turtyo** [Saplings-Projects/1M_sub#81]
## Feature Description

An introduction animation for the game when it is launched.

## Motivation

Currently the splash art loading time is not constant and is dependent on the speed at which your computer can launch the game. This is pretty short, and we don't have much time actually to see the splash art (which is a shame because it looks nice).

## Concept art / Designs

![image](https://github.com/Saplings-Projects/1M_sub/assets/49365680/010dbe18-f87b-4029-9f9c-f5bd4f8e78a2)

The actual loading could be a black screen, then we do a fade from black to the splash art, old it for a few seconds and load the first game scene (menu or testing scene depending on when this is implemented compared to other PR).

## Acceptance Criteria

[Define the criteria that need to be met for this feature to be considered complete.]

- We have time to see the splash art
- The first scene then loads normally

## Proposed Solution

I'm not exactly sure how to do this as I haven't looked into solutions yet. I know there are timers in Godot, so we can probably load this intro animation as the first scene with a default timer, and when the timer expires we switch the menu.
The fade from black could be done using shaders but that seems overkill, there might be a simpler solution.

## Additional Context

This issue might need the scene switcher #74

**Comment by Turtyo** [comment]
mmh the actual splash is would be a black screen, and you can't skip that
the intro cutscene  (basically showing the logo) could be skipped probably, but it'll be short so I don't really think there is an interest in giving the ability to skip

**Comment by JonaLam** [comment]
I think letting the logo be skipable could be nice, and then in turn we can leave it a bit longer on screen for the people who wants to see it. It's probably fine either way though.

**Comment by Turtyo** [comment]
I think we should make a normal version first and work on making it skippable later on
Plus we might decide we don't want it skippable if we keep it on screen for a short amount of time

**Comment by Tysterman74** [comment]
How long do you think we want to leave the splash logo on for?

**Comment by TripleCubes** [comment]
> mmh the actual splash is would be a black screen, and you can't skip that the intro cutscene (basically showing the logo) could be skipped probably, but it'll be short so I don't really think there is an interest in giving the ability to skip
> 
> And yes, a shader would probably work well, or maybe we can just have a video player play the fade-in which we did at another place The advantage of doing it with a shader is that we can control the fade time and the total cutscene duration directly within the game code, without having to re-export a video each time

Just make the loading logo as the first scene, use a tween to control the fading, and use a timer to open the menu scene. Why do we need a shader for this??

**Comment by Turtyo** [comment]
Yes I just recently started using tween in the last issue I'm working on. We already used them for card animations, but I didn't realize how powerful of a tool that was.
Putting the loading scene as the first scene and using a tween after a timer to fade to the game menu is probably the best solution.
@Tysterman74 are you ok with that ? I don't know if you started doing things already on this issue

**Comment by Tysterman74** [comment]
Ya that seems simple enough, I'll need to look into how to doing that. I haven't started any work on it yet.

**Comment by Turtyo** [comment]
You can check what I did for the XP PR when I open it if you want an example (though there are already some good resources on the net)

**Comment by TripleCubes** [comment]
Relevant links
https://docs.godotengine.org/en/stable/classes/class_tween.html
https://docs.godotengine.org/en/stable/classes/class_timer.html

**Comment by Tysterman74** [comment]
Ok just so I can get solidify the details here. Is the ask for this issue to have a new Splash Scene and add in the Splash logo and do the work there? Currently, our settings have a Boot Splash of a still image of the logo set to display so technically we kind of already have a splash:

![image](https://github.com/Saplings-Projects/1M_sub/assets/5923102/efc18460-a0cd-48e7-8a1a-2e39768b932f)

The starting scene in the Run settings has it set to the MainMenu scene. Are going to have the new Splash Scene be the first scene to start up instead then we just run tween/timer to start the MainMenu scene?

![image](https://github.com/Saplings-Projects/1M_sub/assets/5923102/93820bf3-6c95-470a-82b6-74da5c89cf95)

**Comment by Turtyo** [comment]
1- The actual game logo is displayed very shortly, we can't control the time, and we can't control the actual intro to the game, which is why we want to have a (new) boot splash. You can leave the game to have the boot-splash it already has to not break continuity, since it only stays for a short time on screen. We then transition to our custom boot scene (the same logo for now, but displayed longer

2- Change the starting scene to be the boot screen then tween / load the main menu
