### ISSUE TITLE
Scene loader for the map

### ISSUE THREAD

**Issue by Turtyo** [Saplings-Projects/1M_sub#87]
## Feature Description

Load all information related to the event of the room you move in.

## Motivation

This is to link the map to the actual scene displayed to the player, meaning there is actual progress, instead of being stuck on the same scene forever.

## Acceptance Criteria

- Clicking on a room of the map loads the related event of the room (it can be a single default scene for now, we'll deal with loading random scenes later)
- Moving to the next room can only be done when the event of the current scene is over (combat finished, dialogue event, etc...)
- Have a debug const to allow dev to still move between rooms, even if the event in the current scene is not over
- Finishing an event shows a reward screen (if the event gives a reward), and shows the map.

## Proposed Solution

The block of the scene switch can be done using a `is_map_movement_allowed` boolean set to true by default when the game starts. We have a function named `toggle_map_movement`. We make two signals, `event_started` and `event_ended`. We connect `toggle_map_movement`to those signals.
Upon receiving a signal, the toggle function will put the boolean to true if it's false, and false if it's true. When we start, the map movement is set to true and the player can choose a room on the first floor. We enter an event, a signal is emitted, the map movement is not allowed anymore. When the event ends, the end signal is emitted and `is_map_movement_allowed` becomes true again, thus allowing the player to move again.
Some events such as the shop can directly emit the event ended signal after the event started, but it shouldn't show the map directly I think;
The DEBUG const can easily be done by having the getter for `is_map_movement_allowed` return `DEBUG_MAP_MOVEMENT_ALLOWED or is_map_movement_allowed`. If the DEBUG is set to true, the getter will always return true since we use a or expression.

When clicking on a room, we check the room we are moving to and the associated event.
We send the associated event information to the GlobalLoader, which will then load the related scene event (which can later be changed to a random selection of the events of the given type).
Sending the information to the global loader also means it can keep track of all the events that have been loaded, and eventually try to not repeat events that have already been selected previously (like to not randomly select the same discussion event for example). That's not to be done now, but it's a consideration for it for later, and the reason I think we should use the global loader for that.

We could also have a common event_init function for all the scenes, that all take the same information, and that is always called by the _ready() function of such scene (which is triggered upon being loaded by the Global Loader).

## Additional Context

This is a follow up of the issue #74

**Comment by Tomzkk** [comment]
I would say overall the proposed solution makes sense. 
I'm not sure what to do about the difference in shop compared to pretty much anything else when it comes to showing the map - maybe we could add a specific "Leave the shop" (or similar in case of other events that don't have regular end) option that would be ending the shop event and showing the map - but that might not work well if player can still view map but can't use it in that case. 
Global loader (with the event list inside of it) might also be helpful if we would end up wanting some events that are related to each other - be it event chains, dialogue options based on something that happened, anything of the kind. 
The loader would also need to be cleaned on game over / restart (unless that already happens by default somehow)

**Comment by Turtyo** [comment]
I think allowing immediate map movement by emitting the `event_ended` signal would work nicely
The thing we could actually do is that each event has a `on_event_finished` function that does the stuff we want after something finished. For a fight it could be to show the reward screen and unlock map movement. For the shop it would just be to unlock map movement.

I know I mentioned the loader choosing the given discussion event upon entering the room, but we could also decide to set everything when first creating the map. That might make it more consistent.
By event chains I'm guessing you mean events that are related between each other ? Like if we have a two parts quest, to make the second part available when the first has been done ?
By cleaned, do you mean to reset the list of visited events and such ? By default for now, the loader doesn't contain such information, it just allows events to call it to ask it to load a specific scene.

In itself the loader doesn't know which scene loads which scene, it just manages the scene loading for the scenes that ask it to load other scenes. So for example, the option menu has a button to go back to the main menu. When we press the button, in the option scene there is "on_button_pressed" which calls the scene loader asking it to load the main menu scene.

**Comment by Tomzkk** [comment]
It can work fine, I was just thinking it would be best if it was consistent. Having it to where after an event/combat the map opens automatically but then in the shop you have to manually open it with the map button and there being no other option to "end the event" and go there naturally might feel a little bit off ? 

Yes, that's what I meant by related events. I know in early stages there were some ideas thrown around along the lines of your actions could affect things down the line, this could also go into the events and similar. I'm not sure if we will have ones like that (as designing those would add complexity), I was just pointing out that if we did add the list of previous events into the loader it could also be used for that purpose. Of course we can also just generate the whole map in advance and then those (if they existed) would have to be dealt with differently.

Yes, I was making a point of if we add context such as list of played out events into the loader (like you suggested in the proposal), then it might be necessary to clean that in case of game ending / restart ?

**Comment by Turtyo** [comment]
Well in the map you *need* to open it manually because we can't know when the player wants to leave. For a combat it's obvious, once you finished the fight and got the reward screen, we just need to open the map (with a `next` button on the reward screen for example). In the shop, the player leaves when they want, so we can't do a map pop-up. If you look at StS, they do exactly this.

If we generate the whole map and the player triggers an event that is in multiple parts, we can just decide to replace an event by another event (and the player won't even see it).
Or we can decide that two parts events are in different levels of the map, so it would totally work to just generate the whole map on each section and replace an event at generation.

And yes, we can clean the loader without problem if we add the list, after all it's just calling a clear function on an array.

**Comment by Turtyo** [comment]
So @Tomzkk what do you think of adding a `on_event_ended` function to all events that gets activated by a `event_ended` signal ?
For now just putting placeholders, but so we know where we are going with that

**Comment by Tomzkk** [comment]
@Turtyo I think we can go with that

**Comment by Turtyo** [comment]
Do you think we can go like that ? If yes, confirm the issue

**Comment by Turtyo** [comment]
I'll try to have that ready as a draft by the weekend, and to finish it during the weekend if there are things to change
