### ISSUE TITLE
Inventory

### ISSUE THREAD

**Issue by Turtyo** [Saplings-Projects/1M_sub#88]
## Feature Description

A node (or most likely a singleton ?) that keeps track of items that the player has.

## Motivation

We need a way to keep track of player inventory state. The current PlayerManager only keeps track of health and stats, but not items, money, torches...

## Acceptance Criteria

- The inventory should have different categories depending on the item type (relic, consumable, money, torches)
- The inventory should be done so that it's not difficult to add a new object category if needed
- Each category has its own trigger functions, that does actions related to the category (relic change stats for example)

## Proposed Solution

We can either:
- Do all the inventory in the PlayerManager
- Make a separate singleton for the inventory

I would be more for the second option. Each category has an associated array / dictionary / int depending on what we want to count, For example
- Torches, money : int
- Consumable: array (to easily remove them), with a size check to make sure we don't have too many consumable (limit could be 3)
- Relics : array

Each category then has associated functions:
- a add / remove function for consumables and torches
- a update stats for the relics

I'm not seeing a lot more functions that would be needed for now. I think it would be good to have a related display for those arrays (so we can the state we are currently in).
For example the torch number would be shown when opening the map, consumable, money, relics could be shown in their own menu or directly at the top of the player's screen (like what is done in StS for example)
![image](https://github.com/Saplings-Projects/1M_sub/assets/49365680/83766ef3-c10a-425d-ba83-0c76b6799d1c)

**Comment by JonaLam** [comment]
Should placeholder classes be made for things like Relics and consumables to staticly type the diffrent arrays?

**Comment by Turtyo** [comment]
Yes I think it should be nice
They probably won't be just placeholders, as Relics will modify permanent stats whereas consumables will modify temporary stats
Plus the number of slots will be different

**Comment by JonaLam** [comment]
Should the stat modification be done in this pr? I assume we're gonna have some more interesting relics in the future, so I think it could be nice to do stuff like that in another pr

**Comment by JonaLam** [comment]
I think I'll do it by making a new auto-load script for the system.

It wil have some basic function, maybe a reset function, a function which can bring out a inventory display, as well as holding the info for all of the inventory catagories

The inventory display wil be a prefab which can be called out with a function, probably similar to how the map works currently, and it wil be modeled around the one from Slay the Spire, with minimal functionality like using potions

I think what would be best for each inventory catagory is to have one script for each catagory and then have the inventory manager hold variables for each of those.
 For eksample: we have a script called "GoldInventoryContainer", which has a var gold : int for gold amount, and then functions like, "get_gold", "lose_gold", "has_more_gold_than", and then the InventoryManager has a var gold_container : GoldInventoryContainer, which other classes can access with InventoryManager.GoldContainer.
I think spliting each part up like this reduces bloat of the main script as well as makes it possible to add new parts to the system without haveing to change anything in the main script, or having to deal with all the other item catagories

There wil also be placeholder functions for thing to made in the future, like consumables and relics, these wil be recources with minimal functionality other than simple stat changes and debug messages. The relic container wil have simple "on_get" and "on_lose" function, and the consumable container will have simple use functions

I might use cards to test some of these, so there might be added some new debug cards like: "get 5 gold", "get a relic"

**Comment by Turtyo** [comment]
By auto-load you mean singleton ? I would put it in Manager as it would probably make sense there.

Instead of naming stuff as container I would say Component to keep it the same as what we already have. I agree with making distinct parts, as it's already what we are doing in a lot of places anyway.

I think using cards for debug doesn't make sense, as you will never get a relic from a card for example. Tests using GUT and calling the functions might make more sense.
If you want to test in game, a debug panel with buttons that call different function will also make more sense than using cards.

Apart from that, seems good to me :+1:
