### ISSUE TITLE
Light mechanic

### ISSUE THREAD

**Issue by Turtyo** [Saplings-Projects/1M_sub#9]
## Feature Description

Players can place a light source in the room they are in currently after the event of said room is finished, which provides light to adjacent rooms. The lit state of the room influences the event in the room by changing the difficulty / loot. Unlit rooms also don't display the icon of their event until you are just next to said room.

## Motivation

The idea of using light has multiple goals:
- It lets the player influence the map, which is an interesting mechanic
- It creates uncertainty, since you can't see the entire map
- It creates a risk/reward situation (using more torches reduces difficulty but the loot is less good)
- It's lore relevant since the story says the tree is corrupted by darkness, lighting it up makes sense. And Fauna also forgot multiple times to light the tree which led to accidents.

## Acceptance Criteria

- Light is placed after event in the current room and before leaving the room
- The rooms outside of the range are not revealed, the rooms in the range show the icon of the event in the room

## Proposed Solution

You start the map at node 0. There is a torch placed here by default and you can see everything up to 3 node in every direction you can move to, so you can plan your route. This area is lit and combats/events are normal difficulty in the light radius.

You work your way up to node 3 and can now only see node level 4 that is dimly lit since it is not within torch radius. Tutorial prompts you that these combats/events will be more difficult but with greater reward (risk reward). Node levels 5 and beyond are in darkness and cannot be seen until you move next to them and they become dimly lit.

Place a torch? Y/N

You place one of your 3 torches, not feeling overconfident, and the next 3 levels are lit up(4-6). You take a path leading to 2 combats on levels 4 and 5, but you mess up the first and are worried. You can place a second torch within the radius of the first, which does 2 things. 1: causes 3 levels away to become lit(5-7). 2: Levels 5 and 6 are now brightly lit because they are in the radius of 2 torches, which makes combat/events easier.

You now have only 1 torch left, which lets you continue up to node level 10 at normal difficulty, or less at easier difficulty. You can buy more at a shop, and combats have a chance to drop one. If you are full and/or don't want the torch drop, you can pass on it for money or something simple. If you have torches remaining at the end of a map, you get extra money or bonus points or something.

## Implementation Steps (Optional)

- Add a level of light for rooms (probably an enum, 0 unlit, 1 dimly lit, 2 lit, 3 brightly lit)
- Make a `light` class to hold data for the light
- Make light interact with the map ie:
    - Lights should update the visibility of rooms
    - The level of light in the room can influences enemies and random event chances

## Additional Context

This issue is in link with the map implementation #6 and should probably be developed on the `map_implementation` branch.

**Comment by Tysterman74** [comment]
Couple of questions!

1. Should this issue also address having a map UI as well? We may not be able to get far on this if we just add `light` object to the rooms. 
2. Using the map_concept room as an example, if we assume a torch at the space above the start and we can see 3 levels up, is this an accurate representation? Yellow marks being lit and Red marks being the dimly lit, everything else being dark.
![map_concept_with_light_1](https://github.com/Saplings-Projects/1M_sub/assets/5923102/47ab83e6-6937-4180-b49b-eb25e4a7d0dd)

**Comment by Turtyo** [comment]
1. UI should probably be handled separately. The issue needs to have a Light class, each room needs to have a light object in it (possibly null, or we could just use a boolean i guess). We also need to be able to update the level of light in rooms. Indeed there is not much, but at least we get a basis to work on.
2. No this is incorrect. From the start point, you can get to any of the room in the first 3 levels (since we can go in diagonal, if you go full right you can we get the room at the extreme right). Also note that a room is only dimly light if: this room is not lit **and** the player is next to it. So from the start position, there are no dimly lit rooms actually. The fact that room can be dimly lit is also something that needs to be made in the PR.

Another point, for the purpose of the display later, we should have a way to let rooms that have been dimly lit still visible to the player, even if he has passed them (they are technically in the dark but the player saw them)

**Comment by Tysterman74** [comment]
Ahhh Okies. I'm fine with just adding the classes for now then! I think a diagram of how we want this light mechanic to look like relative to the map would help.

**Comment by Turtyo** [comment]
You mean a drawing of how a torch would light the map ?

**Comment by Tysterman74** [comment]
Yeah! I think it would for the implementation whenever we get to the UI portion of it.

**Comment by Turtyo** [comment]
That's making me think, I need to update the documentation, because the image I posted there was wrong!
Here is the new updated explanation, that will go in the doc (PR to come)
![light_mechanic_explanation](https://github.com/Saplings-Projects/1M_sub/assets/49365680/9e51c1c7-cbfa-465e-829c-6f077c5f46da)

**Comment by Turtyo** [comment]
@Tysterman74 is it clear like that ?
I also changed a criteria on the original message (clicking on the map to put the torch)
Since you can only put a torch in the room you are currently in, it wouldn't really make sense to click on the map for that

**Comment by Tysterman74** [comment]
@Turtyo That is SO much clearer, thank you! 

One question though, on that last picture we put a torch at level 2. However, some of the rooms weren't colored in yellow. Is there a reason for that? I thought that was still part of the levels to be lit if we put a torch on level 2.
![image](https://github.com/Saplings-Projects/1M_sub/assets/5923102/45d83f7f-f449-4270-bcb6-0b38da52b82e)

**Comment by Turtyo** [comment]
If you look at the room that are accessible from the position of the second torch, the rooms of the left are not accessible. The rooms accessible are a cone between full left and full right. Thus rooms on the very left side wouldn't be accessible, they stay in the dark.

**Comment by Tysterman74** [comment]
I think with how map implementation is going, I may be taking this issue as well. Could I get a few more examples of the light mechanic? I noticed the image we have in the documentation images folder is different from what you have here on this issue so Im a bit confused on the mechanic still.

**Comment by Turtyo** [comment]
is it different ? maybe I just updated the doc on the main but not on the `map-implementation` branch, because i remember doing a PR for that recently.
I think rather than me showing more examples, it would be better if you give me examples where you have a doubt on how the light should be, it will probably be more efficient that way.

**Comment by Tysterman74** [comment]
Ah I was on `map-implementation` so it's outdated then.

Just need some sanity checks on the light then. For this picture: That circled M room in red does NOT get light, because the player can only go up, up-left, and up-right?

![image](https://github.com/Saplings-Projects/1M_sub/assets/5923102/6944266c-2a2b-4db0-85fc-ac509282f625)

And same for the the brightly lit room, we can only light up areas that are up, up-left, and up-right?

For the Mini-Boss room, should that also be lit up as well?

**Comment by Turtyo** [comment]
Yes as you showed with 1, 2, 3, even going full left you don't reach the room circled red, meaning the light doesn't reach it either
For the brightly lit rooms, the only rooms that are both accessible through a three movement step are the ones in light blue.
Note that technically once you put the second torch, the room with the second torch is also brightly lit. Not sure if it matters, since we put torches before leaving the room, but i thought I might as well say it

**Comment by Tysterman74** [comment]
That's good to clarify! Okay I think I have a good idea of how it works now.

**Comment by Turtyo** [comment]
Do you think the documentation needs more precision on some points since it didn't seem obvious from the image alone ?

**Comment by Tysterman74** [comment]
Yeah mentioning movement between rooms would help. I had the assumption we could go left or right from the same floor, so i was confused how that tied in with the range of light.

**Comment by Turtyo** [comment]
There is a reminder written on the bottom left
it's probably too small, I will make it bigger

**Comment by Turtyo** [comment]
oh yeah @Tysterman74 how do you plan on doing this in the end ? I was thinking you might need something to do with the possible player movements
The player movements will also be useful when we actually need to move on the map, and I'm thinking it might better to do map movement before doing the light ? because you will need to move anyway to put torches and see the effect of light. We might need to open a PR for just the movement on the map ? And being able to click on the map to move to a room also

**Comment by Tysterman74** [comment]
Right now I have RoomUI as a packed scene where it has a click handler for placing a light. We can do player movement or light placement within that packed scene and have the requisite checks if we're able to navigate there or not once we iron out those details. 

Currently I'm just working on when placing a light there to show the eligible rooms.

**Comment by Turtyo** [comment]
I see
I'll open an issue for the player movement on the map then, it can be done separately

**Comment by Tysterman74** [comment]
I can add in more details on that issue once I get a draft PR up for this issue. For the new issue with player movement, did we want to start looking into resolving the room event we get when we navigate to that room?

**Comment by Turtyo** [comment]
I was thinking of loading a related scene when moving to a room with a certain event

**Comment by Tysterman74** [comment]
Gotcha. Would that be done in the issue for navigating to rooms or a different issue?

**Comment by Turtyo** [comment]
The same, as a way of testing everything works, will discuss this more in the new issue
