### ISSUE TITLE
In editor documentation

### ISSUE THREAD

**Issue by Turtyo** [Saplings-Projects/1M_sub#90]
## Is your amelioration related to a problem? Please describe.

The only documentation we have for now (started with #32 ) is only superficial and doesn't describe everything accurately.

## Describe the solution you'd like

Use Godot's built-in documentation system to document all the functions and variables (see [the documentation comments page](https://docs.godotengine.org/en/stable/tutorials/scripting/gdscript/gdscript_documentation_comments.html)

## Additional context
I wanted to use [GDQuest's gdscript-docs-maker](https://github.com/GDQuest/gdscript-docs-maker) to generate the doc, but it doesn't seem to work with Godot 4.2 for now, so we will need to wait if we want to do that, or find another solution (maybe [the GDScriptify tool](https://github.com/hiulit/gdscriptify) ? I haven't tested it yet, and the last update was 3 years ago so it probably won't work).

I will start documenting on the code I'm confident I know (so most of the cards code, stats etc...)
I'll also start on the map, but I might leave some parts about the map UI to @Tysterman74 though he has commented the code nicely already iirc, so i might be able to just write it like that
For the animation part, it would be best if @cheesefrycook could do it as he probably knows this the best

**Comment by Tysterman74** [comment]
If there's other areas you need me to look at and comment on, let me know!

**Comment by Turtyo** [comment]
I'll be sure to ping you if I need help on some areas !

**Comment by Turtyo** [comment]
i'm wondering if we should close this as most of the job is done and just complete the rest as we go ?

**Comment by Turtyo** [comment]
I decided to close this as most of the documentation is done and documentation should be added to functions as they are being worked on.
