### ISSUE TITLE
Finishing combat by killing enemy with poison freezes game

### ISSUE THREAD

**Issue by Turtyo** [Saplings-Projects/1M_sub#95]
## Describe the bug
If you kill the last enemy of the scene with poison damage, you get an OOB error on the enemy index, which freezes the game.

## To Reproduce

1. Launch a mob event
2. Kill all the enemies expect one
3. Put the last enemy in the range where it can be killed by poison damage
4. Let the poison do its thing
5. When the discard is taking place, the game freezes

## Expected behavior
The game shouldn't crash.

## Screenshots
Error:
![image](https://github.com/Saplings-Projects/1M_sub/assets/49365680/acddf9e1-1f91-4591-93ce-e9e268a070f9)
Stack trace:
![image](https://github.com/Saplings-Projects/1M_sub/assets/49365680/8c16f1ae-ef51-4685-9bf9-27504ea4ec25)
![image](https://github.com/Saplings-Projects/1M_sub/assets/49365680/321072a8-eb49-402d-888b-2958497f5e8b)

## Environment
 - Linux
 - Main on commit [6e146f9](https://github.com/Saplings-Projects/1M_sub/commit/6e146f90d80ae9ebd333ecf718c30b3f24f91512)

## Additional context
There is probably a mistake in the order in which the check for the enemy death and the `on_turn_start` is handled. 

My guess of what happens is that the `on_turn_start` killing the enemy due to poison damage is done, then the enemy tries to attack but the check to see if the enemy died doesn't stop the execution of the rest of `on_turn_start` thus the non-existent enemy tries to attack while being dead.

**Comment by Marineline** [comment]
Reproduced the same error
![image](https://github.com/Saplings-Projects/1M_sub/assets/90681429/7dc4bef6-18d7-4424-bd67-3bca79f5436d)
