### ISSUE TITLE
End  / credit screen

### ISSUE THREAD

**Issue by Turtyo** [Saplings-Projects/1M_sub#99]
## Feature Description

Wow look at all the people that participated, wow !

## Motivation

We need to credit everyone properly.

## Concept art / Designs

![image](https://github.com/Saplings-Projects/1M_sub/assets/49365680/c93a08a2-f7d1-4aac-93ed-e33b8da3db79)

## Proposed Solution

A new scene with an animation player. Order of the members is random, a few animations that are selected randomly too (the credit scene is never the same).

## Additional Context

Think of properly crediting the dialogue manager, see [this link](https://github.com/nathanhoad/godot_dialogue_manager/blob/main/docs/FAQ.md#how-do-i-credit-dialogue-manager-in-my-game)
Will also need to credit the [smooth scroll addon](https://github.com/SpyrexDE/SmoothScroll)

**Comment by TripleCubes** [comment]
The credit screen should also include the credits for godot and the third party libraries we use. As Godot is MIT licensed, the requirement is that the Godot's license text is included in all source code and binaries we distribute. Also you should check all of the licenses and its requirements of the third party libraries

https://godotengine.org/license/

Also, you should read this document below to the end of it

https://docs.godotengine.org/en/stable/about/complying_with_licenses.html

At the Third party licenses section, they do say that you will also need to include the license text of Freetype, ENet and mbed TLS

**Comment by Turtyo** [comment]
We already thought for the third libraries, they use MIT (see the first message of this issue, there are links at the bottom).
MIT says that we need to include the license "somewhere" in the game. That also includes having it as a text file available in the game directory, it doesn't necessarily need to be visible from within the game, just be shipped with it.
So we don't need to include it in all source code (even though some do).

I didn't know about the third party licenses, thanks for the link ! I also notice we have to include it somewhere in the credit screen (so probably at the end after everyone's name).

Regarding the technical aspect of how to do the credit screen, I was thinking either a fixed screen with the names on it, and we do fade in / out between screens until everyone's name is done. Or we do an infinitely scrolling screen (a bit like you have at the end of movies). I think we discussed it a bit with the design team, but I don't remember us reaching a final idea. We'll have to discuss it again, before thinking of an actual code implementation, because it's not very useful to think of two solutions at the the same time.

**Comment by TripleCubes** [comment]
Im pretty sure everywhere you distribute the third party library, which include both source code and compiled binaries, we need to include the MIT license text of that library

We are distributing the libraries in the addon folder of our repository, which mean our repository must have the third party libraries's MIT license text

**Comment by TripleCubes** [comment]
Sorry my wording is not clear. What I mean is, if you distribute the code of a library in a repository, that repository will need to include the library's MIT license text

And if the library is compiled into the game's binary, the distribution of the game'a binary must include the library's MIT license text too

**Comment by Turtyo** [comment]
Putting the license text at the root of the project's source file and next to the binary should suffice then. I don't think it's required to include it in each sub-directory that uses a different license

**Comment by TripleCubes** [comment]
Yeah yeah. We only need to put the license texts in one location inside our repository. To clarify I am talking about the licenses of all addons in the addon folder, and the license of Godot engine, and godot's third party licenses (FreeType, ENet, mbed TLS), and license of any other third party stuff I am not aware of

Also, these license files need to be availabe in the game distribution too (The zip file that contain the game binaries that Fauna and other players will download on itch.io)

**Comment by TripleCubes** [comment]
"The Godot Engine developers consider that a link to godotengine.org/license in your game documentation or credits would be an acceptable way to satisfy the license terms"

Also be aware that they do said in the https://godotengine.org/license/ page that the page is not a legal advice, it only explain godot team's understand of their license and their third party licenses. Read the disclaimer at the bottom of the page

I say will still include the MIT license of godot and the text of FreeType, ENet, mbed TLS just in case

**Comment by TripleCubes** [comment]
> I don't think it's required to include it in each sub-directory that uses a different license

What do you mean sub-directory that use a different license?

**Comment by Turtyo** [comment]
Like we don't need to put the license of each add-on it its own subdirectory. If two things use MIT, we only need to put the MIT once

**Comment by TripleCubes** [comment]
You should look at the MIT license file of each of these libraries. In addition to the license text, there is a `(c) Copyright Project Owner name` text too. That is different to each library and we need to include all of them

The MIT text itself can be included only once tho

**Comment by TripleCubes** [comment]
Actually, reading the requirements of the MIT license, Im not sure if it require the license file itself to be included in the project that use the library or not. But it might require it. So we should probably just include all MIT license files just to be safe

**Comment by Turtyo** [comment]
yeah the actual wording is "The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software."
To prevent forgetting to put the file with the zip, the best would probably be to have a license screen in the options that you can access
That way the license is always with the game

**Comment by Turtyo** [comment]
Storyboard for the credit scene
![image](https://github.com/Saplings-Projects/1M_sub/assets/49365680/ea30bbd6-6aa5-4546-870b-a23d07b00c2c)
It will transition to a black screen with the other information that is needed after
